### ISSUE TITLE
add option to select language

### ISSUE THREAD

**Issue by JohanDegraeve** [JohanDegraeve/xdripswift#108]
for example user is set to Spanish but it may still be preferred to use the app in English

**Comment by Jon-b-m** [comment]
This is very easy to add (PR probably not needed, but I can make one if you want): 
in Xcode add new file/Resources/Settings Bundle, choose name (settings.bundle for instance). 
And that's it!

**Comment by Jon-b-m** [comment]
Made a PR now...

**Comment by JohanDegraeve** [comment]
Apparently changing app language is possible in iOS settings since iOS 13
