### ISSUE TITLE
Pull backlogged Watlaa data and upload to Nighscout

### ISSUE THREAD

**Issue by paulplant** [JohanDegraeve/xdripswift#112]
Post from Jay Haines in the xDrip4iOS Facebook group.

When phone is left disconnected from Watlaa, xDrip4iOS does not recover the backlog data (shown in Watlaa) and upload to Nightscout upon reconnection.

[https://www.facebook.com/groups/853994615056838/permalink/965913043864994](url)

**Comment by JohanDegraeve** [comment]
confirmed on facebook,  recovering backlog data works correctly
