### ISSUE TITLE
Threshold lines

### ISSUE THREAD

**Issue by clvsjr9** [JohanDegraeve/xdripswift#114]
Would it be possible to have dashed style threshold lines to assist the diabetic's graphic interpretation?

**Comment by JohanDegraeve** [comment]
@paulplant  is working on enhancements in the graphic.
dashed lines are part of it

**Comment by JohanDegraeve** [comment]
see commits
da7e5a09bd837faac90cff79fce4411a874f19fe
cbf43f4554fc6515e1b4c561741d81878ed10fc6
e939ac95955a5cab08ab320e8c78524bf086b4b3
