### ISSUE TITLE
new BG value: On-demand request

### ISSUE THREAD

**Issue by clvsjr9** [JohanDegraeve/xdripswift#115]
Would it be possible to have an on-demand manual request for a new BG value from transmitter? (equivalent function that exists in three dots menu of Spike app)

**Comment by JohanDegraeve** [comment]
Is possible but there is a much easier way : disable and re-enable bluetooth.
It only works for MM and Bubble. By disabling/re-enabling bluetooth, the connection will be dropped/re-established
When re-establishing, xdrip asks a new reading.

Much easier : not even needed to unlock your phone. And no coding required

**Comment by clvsjr9** [comment]
Excelent. Simple and totally effective.
