### ISSUE TITLE
xdripswift <<<--->>> FreeAPS/Loop integration 

### ISSUE THREAD

**Issue by clvsjr9** [JohanDegraeve/xdripswift#116]
Suggest a simple adjustment in Info.plist file to ease to use:
 
Details at:

https://github.com/julian-groen/xdrip-client-swift/issues/1#issuecomment-646149084

**Comment by JohanDegraeve** [comment]
based on feedback given by Julian Groen, I think this issue can be closed ?

**Comment by clvsjr9** [comment]
Very thanks!
