### ISSUE TITLE
Upload calibration data to Nightscout

### ISSUE THREAD

**Issue by Andrei0105** [JohanDegraeve/xdripswift#117]
Hi!
Currently, xDrip doesn't upload any calibration data to Nightscout - neither the BG value, nor the slope and intercept.
Without seeing this data, it's impossible to trust that xDrip is taking the right decisions when calibrating. It's also not possible to check if a new calibration resulted in an incorrect calibration slope.

I would like xDrip to upload data to Nightscout, just as Spike is doing.
For each calibration Spike was adding:
- to the treatments collection (example with filled data):
```
{
    "eventType": "BG Check",
    "enteredBy": "Spike",
    "created_at": "2020-06-22T09:10:42.000Z",
    "notes": "Sensor Calibration",
    "glucose": 86,
    "glucoseType": "Finger",
    "utcOffset": 0
}
```
- to the entries collection (example with filled data):
```
{
    "scale": 1,
    "dateString": "2020-06-22T09:10:42.000Z",
    "device": "MIAOMIAO",
    "date": 1592817042408,
    "intercept": 36243.38657894716,
    "slope": 926.7628630543243,
    "type": "cal",
    "utcOffset": 0,
    "sysTime": "2020-06-22T09:10:42.000Z"
}
```

I suggest that xDrip should upload the following data for a calibration:
- to the treatments collection:
```
{
    "eventType": "BG Check",
    "enteredBy": "xDrip4iOS",
    "created_at": [date],
    "notes": "Sensor Calibration",
    "glucose": [glucose value],
    "glucoseType": "Finger",
    "utcOffset": [utc offset]
}
```
- to the entries collection:
```
{
    "scale": [scale],
    "dateString": [date],
    "device": [device type],
    "date": [date ms],
    "intercept": [intercept],
    "slope": [slope],
    "type": "cal",
    "utcOffset": [utc offset],
    "sysTime": [sys time]
}
```

Thanks!

**Comment by m-a-v** [comment]
I think there is a bug in the implementation of Spike. Something with the scaling seems not to be okay.

See also this issue here:
https://github.com/SpikeApp/Spike/issues/145

**Comment by Andrei0105** [comment]
You are right @m-a-v 
Spike isn't uploading a mbg value which seems to be required to be able to draw the calibration slopes in Nightscout.

This is what xDrip+ (for Android) uploaded to NS for a calibration:
- to the entries collection:
```
{
    "_id": {
        "$oid": "5e3287143ca3b98fc2fd5f70"
    },
    "device": "xDrip-LimiTTer",
    "type": "mbg",
    "date": 1580369408034,
    "dateString": "2020-01-30T07:30:08.034Z",
    "mbg": 72,
    "sysTime": "2020-01-30T07:30:08.034Z",
    "utcOffset": 0
}

{
    "_id": {
        "$oid": "5e3287143ca3b98fc2fd5f75"
    },
    "device": "xDrip-LimiTTer",
    "type": "cal",
    "date": 1580369408034,
    "dateString": "2020-01-30T07:30:08.034Z",
    "slope": 944.7112501164377,
    "intercept": 43628.04319389094,
    "scale": 1,
    "sysTime": "2020-01-30T07:30:08.034Z",
    "utcOffset": 0
}
```

So xDrip+ is only uploading the glucose value to the entries collection. This means that Nightscout will be able to draw the slope. I would still like to have the BG value in the treatments collection so it is displayed in the Nightscout interface.

Considering the changes, I suggest xDrip4iOS to upload the following data to Nightscout for each calibration:
- to the treatments collection:
```
{
    "eventType": "BG Check",
    "enteredBy": "xDrip4iOS",
    "created_at": [date],
    "notes": "Sensor Calibration",
    "glucose": [glucose value],
    "glucoseType": "Finger",
    "utcOffset": [utc offset]
}
```
- to the entries collection:
```
{
    "device": [device type],
    "type": "mbg",
    "date": [date ms],
    "dateString": [date],
    "mbg": [glucose value],
    "utcOffset": [utc offset],
    "sysTime": [sys time]
}
{
    "scale": [scale],
    "dateString": [date],
    "device": [device type],
    "date": [date ms],
    "intercept": [intercept],
    "slope": [slope],
    "type": "cal",
    "utcOffset": [utc offset],
    "sysTime": [sys time]
}
```

Regarding the linked issue, I created this app https://github.com/Andrei0105/cgm-calibration (live here: http://cgm-calibration-stats.azurewebsites.net/, many bugs to be fixed) to be able to visualize Spike calibration data. I would like to be able to use it for xDrip4iOS also, and uploading data to Nightscout should be simpler than implementing a xDrip+ like visualization in xDrip4iOS.

**Comment by JohanDegraeve** [comment]
see commit 34efb3a3793b9e58b608bb85046204fb9aa92ab2
