### ISSUE TITLE
Double Notifications

### ISSUE THREAD

**Issue by hansdampf01** [JohanDegraeve/xdripswift#123]
Actually I think thats working as intended and Im more asking for an enhancement.
Xdrip sends a notification for each reding to my home screen. However when you are also in a high or low area a second notification will be triggered right after the reading notification. Can this somehow combined so Im getting a reading as High Alarm instead of both?
This will greatly reduce the amount of notifications ( for me its vibrating in 99% of the time).
Also an Option to disable the normal reading would be great so you have the option to go fully silent and just look at the apple watch calendar solution.

**Comment by JohanDegraeve** [comment]
will be fixed in next release so that if an alarm goes off, the normal notification is not shown, so there will be only one notification.

the normal notification can already be disabled
