### ISSUE TITLE
Bluetooth Alias lost after disconnect

### ISSUE THREAD

**Issue by hansdampf01** [JohanDegraeve/xdripswift#125]
Im using 2x MM2 and swap them every new Sensor.
I gave both MM an alias inside the Bluetooth settings.
Those aliases are lost after disconnect and I can only different them via mac address or when I move one MM out of Bluetooth range.

**Comment by JohanDegraeve** [comment]
Aliases are lost ? are you sure ? 
could you send a trace file ?

**Comment by hansdampf01** [comment]
You are right, It will only be lost when I actually delete it and would expect that. 
When I disconnect it still shows my alias.
My bad. Sorry.
