### ISSUE TITLE
Enchance Calibration Warning for Libre 2 Sensor

### ISSUE THREAD

**Issue by hansdampf01** [JohanDegraeve/xdripswift#126]
It would be great to add to the warning message "With OOPWeb enabled, calibration is not necessary for the Libre Sensor"
"Libre 2 Sensor can only work with OOPWeb and cant be calibrated" or something similar.

**Comment by JohanDegraeve** [comment]
Actually it is possible to calibrate, even if oop web is used (if i'm not mistaking, I don't have a Libre 2 for the moment to test)

i've changed the text with this sentence  : "With OOPWeb enabled, calibration is not necessary for the Libre sensor. If you still want to use calibration, then go to the Developer settings and enable 'Override Web OOP Calibration'."

**Comment by JohanDegraeve** [comment]
fixed in 052a1800a4e84075ca0d588b7f4a152e20b28570
