### ISSUE TITLE
Enhancement - Volume Override

### ISSUE THREAD

**Issue by hansdampf01** [JohanDegraeve/xdripswift#127]
I would love to see a system volume override for alarms.
E.g. im listening a podcast when going to bed but want the sound to be low. However I want my alarm to be loud and being able to set volume independently from system volume.

**Comment by JohanDegraeve** [comment]
Please check the documentation available in the FB group. There's an option to test the alarm volumes.
There's no possibility on iOS to override system volume.

**Comment by hansdampf01** [comment]
Hey Johan,

Im not sure if it is actually a workaround but the Libre Stock app does it for the emergency alarms and will be max volume. Also Spike app does have it as an option to override system volume. But not sure on which way they probably implemented that.

**Comment by JohanDegraeve** [comment]
I'll have to check, if it's in Spike then I can see how it works there

**Comment by JohanDegraeve** [comment]
I tried out the methodes used in Spike but didn't get it to work.
Also according to Apple documentation, it is not possible to set a volume higher than the system volume.

I'll close this issue
