### ISSUE TITLE
alerts: decouple vibration pattern from sound effect

### ISSUE THREAD

**Issue by 4gra** [JohanDegraeve/xdripswift#146]
It would be nice - for several reasons - if the vibrate pattern for alerts could be set independently of the alert tone.  

Amongst the set provided in many cases there doesn't seem to be any connection between the vibrate and the audio - and even when there, is that might not be desirable (for example someone who sets a strong, noticeable vibrate pattern might do so because they need to notice an alarm, but _don't_ want everyone around them to hear a loud siren tone just because the phone happens not to be on mute, perhaps for actual telephone-related reasons!).

* So in the first instance replacing the 'alert' chooser with one for sounds and one for vibrate patterns would be highly desirable. 

* Ideally this chooser should also present a preview of the vibrate pattern, which is probably a separate enhancement as there's currently no way I've found to preview vibration patterns from the alert chooser.

* Ideally this should be free-form customisable (i.e. "compose your own") in the same way as iOS notifications, but I appreciate that's probably no longer possible if https://github.com/JohanDegraeve/xdripswift/issues/124#issuecomment-663731625 is correct.

**Comment by 4gra** [comment]
Looking at the relevant APIs it certainly looks like a lot of work to separate the two - but if all that came out of this issue was that the alert chooser also allowed the user to preview the vibration as they scrolled through the alerts, that would be a big improvement for those who rely more on vibration than audio.

**Comment by 4gra** [comment]
Hi, I suppose you owe your users nothing -- but if you've got a rationale for the WONTFIX I'd be keen to know.

**Comment by JohanDegraeve** [comment]
for me, it's too much work compared to the benefit.
The project is open for others to contribute, but as there's not been a proposal the last two months I prefer to close the issue. I'm doing a clean up in the issues. It's better than keeping them open which may give the impression that they will still be worked on

**Comment by 4gra** [comment]
No problem. If I ever get some Mac hardware new enough I'll try to dive in :)
