### ISSUE TITLE
Just temporary placeholders for Libre 2 characteristics UUIDs?

### ISSUE THREAD

**Issue by gui-dos** [JohanDegraeve/xdripswift#147]
I am not into reverse engineering and I am using simple visual tools like jadx-gui.

I can see easily that LibreLink uses two BLE characteristics named "BLELogin" (0xf001) and "CompositeRawData" (0xf002) to communicate with the Libre 2. After writing into the first characteristic an "unlock payload" they are getting by calling a native method, they are reading three data packets from the second characteristic.

In your commits ef8f6eb you are using the standard Droplet characteristic UUIDs: are you actively working on a direct connection with the Libre 2 and simply using placeholders in the meantime?

**Comment by JohanDegraeve** [comment]
Not actively testing

Just a placeholder



Op za 19 sep. 2020 om 11:35 schreef Guido Soranzio <notifications@github.com
