### ISSUE TITLE
The starting digit of the Libre 2 serial number should be "3"

### ISSUE THREAD

**Issue by gui-dos** [JohanDegraeve/xdripswift#160]
The starting digit of the Libre serial number reflects the product family of a sensor which is "3" for the Libre 2, not "0"; it is "1" for the Libre Pro, for example, and "7" for the new LibreSense.

**Comment by JohanDegraeve** [comment]
what is the issue exactly ?

**Comment by gui-dos** [comment]
@UPetersen reducing algorithm should start with the product family code (https://github.com/JohanDegraeve/xdripswift/blob/cee941e99b3dd580f9488593179c02d291f31746/xdrip/BluetoothTransmitter/CGM/Libre/Utilities/LibreSensorSerialNumber.swift#L90).

Take a look for example at this implementation: https://github.com/bubbledevteam/bubble-client-swift/blob/e5f70449cc46f395d79444c9627ca5d15580537a/LibreSensor/SensorSerialNumber.swift#L92-L108

**Comment by gui-dos** [comment]
Besides from its name, you can get the right sensor serial number by reading the standard GATT characteristic 0x2A25.

The sensor UID is also transmitted in the manufacturer advertised data; you have to append  [0x07, 0xe0] to the last six bytes.
