### ISSUE TITLE
How to get libre 2 working with miaomiao?

### ISSUE THREAD

**Issue by opsb** [JohanDegraeve/xdripswift#162]
Hey, I've been using the libre 1 sensors with xdripswift for a long time but they've stopped selling them in Spain now. I've got my first libre 2 sensor and while xdrip is able to connect to the miaomiao it always says that the sensor hasn't been started. I'm able to read the sensor in the libre linkup app so the sensor has definitely started. I'm using master (at cee941e today) and I've obviously tried resetting the miaomiao but it hasn't made any difference.

If you're using a libre 2 how did you get it working? Did you have to update the firmware and if so did you find a way to do it with an iphone?

**Comment by JohanDegraeve** [comment]
I think you probably need a firmware upgrade to 07 ?
Let me know if you need the files for that.

But you can also connect directly to the Libre 2. Disconnect the MM (go to the bluetooth screen and click 'disconnect' - it's not necessary to delete the MM)

and add a new CGM, type Libre2, do NFC scan, wait (should be maximum 1 minute) and it should connect

and close the Libre app, or disallow bluetooth permission for the libre app.

**Comment by opsb** [comment]
Hey @JohanDegraeve I couldn't find any way to upgrade the firmware on an iphone or mac. If you have some files that would help me do that they'd be very appreciated.

**Comment by opsb** [comment]
BTW, do you mean to say that it will connect to the libre2 directly via bluetooth? (that seems too good to be true)

I did try your instructions for adding it as a Libre2 but I got an error, presumably because my firmware is too old.

**Comment by JohanDegraeve** [comment]
it is true. but can you switch to Messenger ?

**Comment by opsb** [comment]
wow, that sound amazing :) Sure Messenger works, I tried finding you but there's several, if you search for my full name there's only one :)

**Comment by Paddylfc** [comment]
Hi there could any one help me out connecting libre 2 to miaomiao 1

**Comment by parapenT1sta** [comment]
> Hi there could any one help me out connecting libre 2 to miaomiao 1

Update it to the latest 0039 firmware using Tomato App.

**Comment by Paddylfc** [comment]
Have u a link to it cheers

**Comment by parapenT1sta** [comment]
> Have u a link to it cheers

https://apps.apple.com/us/app/tomato-app/id1474342049

**Comment by glajtman** [comment]
> I think you probably need a firmware upgrade to 07 ? Let me know if you need the files for that.
> 
> But you can also connect directly to the Libre 2. Disconnect the MM (go to the bluetooth screen and click 'disconnect' - it's not necessary to delete the MM)
> 
> and add a new CGM, type Libre2, do NFC scan, wait (should be maximum 1 minute) and it should connect
> 
> and close the Libre app, or disallow bluetooth permission for the libre app.

I would like to ask you about file to upgrade mm2 to V7. And maybe a software and manual how can I do this? Thank you in advance.
