### ISSUE TITLE
App asks for calibration in Follower mode

### ISSUE THREAD

**Issue by CoreISP** [JohanDegraeve/xdripswift#167]
v: 4122
When switching from Master to Follower mode, the app keeps giving alarms that calibrations are needed. No sensor was started in Master mode, in fact: on this particular device I hadn't used the app for weeks. When switching it from Master to Follower it did warn that it might stop the current sensor. (But I guess that's a default warning.) 

There doesn't seem to be a way to make it stop doing this, it just keeps warning about it. Of course I can probably remove the entire alarm, but I guess that shouldn't have to be necessary. 

Not sure if normal, but it also still shows the fields for Nightscout API whilst its set to Follower mode. My best guess is that since those were filled out, it didn't empty them on switching to Follower. That, or something is hanging. I built another one directly from source (different identifier and app name) and started it as follower - those fields disappear instantly and it doesn't complain about calibrations.

**Comment by JohanDegraeve** [comment]
Fixed in commit 58483f58d5e792d15e6d51b09704a171d54dffd1

For the last question about NightScout API fields in follower mode, looks normal as you need NightScout in Follower mode ? If you still think there's an issue, can you make a seperate issue ?
