### ISSUE TITLE
Missing strings for translation on Portuguese (pt) language

### ISSUE THREAD

**Issue by parapenT1sta** [JohanDegraeve/xdripswift#170]
https://github.com/JohanDegraeve/xdripswift/tree/master/xdrip/Storyboards/pt.lproj

Comparing with English:

https://github.com/parapenT1sta/xdripswift/tree/develop/xdrip/Storyboards/en.lproj

**Comment by parapenT1sta** [comment]
@JohanDegraeve Can you merge all the missing strings and files?

**Comment by JohanDegraeve** [comment]
see develop branch
missing files are added.
For the existing files, to verify the missing strings, this requires a visual check - can you do this ?

**Comment by parapenT1sta** [comment]
Thank you. Yes I can check. There are missing strings.

**Comment by JohanDegraeve** [comment]
I'm trying a script that will add the missing strings.
You can already start with the strings that are available now

**Comment by parapenT1sta** [comment]
@JohanDegraeve I had to manually copy paste from english file to the portuguese files.
 Btw, all other languages are missing the same files. It will be possible to automaticallly add new strings in case there are new strings to be translated?
 
  I need your help. What I should translate here? https://github.com/parapenT1sta/xdripswift/blob/develop/xdrip/Storyboards/pt.lproj/Main.strings
  
On this example: /* Class = "UILabel"; text = "Title"; ObjectID = "0QS-QO-ffs"; */ "0QS-QO-ffs.text" = "Title";
