### ISSUE TITLE
Where does 117.64705 come from?

### ISSUE THREAD

**Issue by mirrajabi** [JohanDegraeve/xdripswift#172]
Hi there,

I've seen both [in your project](https://github.com/JohanDegraeve/xdripswift/blob/ba1bf9e399222e2f703e05a1eae7772f62f03dc3/xdrip/Constants/ConstantsBloodGlucose.swift#L4) and [in the xDrip Android](https://github.com/NightscoutFoundation/xDrip/blob/2d0bf3f18a137f88eb7bd5d7f0309a1b28ee9194/app/src/main/java/com/eveningoutpost/dexdrip/Models/LibreOOPAlgorithm.java#L223) that the raw value is multiplied by the constant: 117.64705.

Where does this number come from?

**Comment by JohanDegraeve** [comment]
I have no idea actually. Maybe it was an estimate based on comparing the value received with the value given on a Libre reader ?

in the end, it probably isn't important.
The value is only used if you use the xdrip calibration algorithm. If you would change it to some other value, and do a restart sensor, recalibrate, I think you should end up with the same result.

But it needs be end up in a value in the 100.000 range

**Comment by mirrajabi** [comment]
I appreciate the answer but it doesn't sound so confident.
Do you know what is the unit of raw value extracted from FreeStyleLibre device?
I've checked out a lot of different codes and articles to see if I can find some common pattern to process raw value and so far I feel like no one actually has an idea what the raw value is or it's just that no one documents it properly.

**Comment by JohanDegraeve** [comment]
be aware that this based on reversed engineering, here some more info https://github.com/UPetersen/LibreMonitor/wiki/Libre-OOP-Investigation
