### ISSUE TITLE
Available on the App Store?

### ISSUE THREAD

**Issue by sjaveed** [JohanDegraeve/xdripswift#188]
Is a version of this app available on the app store?  I'd rather not deal with the 30 day expiration of self-compiled apps but will if I have to.

Thanks for the app though - this is amazing work!

**Comment by JohanDegraeve** [comment]
No not available on the App store and it never will be

**Comment by sjaveed** [comment]
Oh interesting.  Clearly you feel strongly about it :-)  Any reasons why?

**Comment by JohanDegraeve** [comment]
Apple would want do a more in depth review. They would need transmitters etc.

**Comment by sjaveed** [comment]
Ah that makes sense.  I wonder if transmitter manufacturers would be interested in providing some for that purpose.  Closing the issue since you've already answered my original question!
