### ISSUE TITLE
Libre 2 : auto snooze alerts for 5 minutes, if new reading occurs withing 5 minutes

### ISSUE THREAD

**Issue by JohanDegraeve** [JohanDegraeve/xdripswift#191]
current situation : 
- high or low alert goes off, but user doesn't snooze
- less than 5 minutes later, high or low goes off again (typically for Libre 2 every minute, but can also happen for bubble/mm/atom, eg after disc- reconnect)

improvement 
- autosnooze for 5 minutes - preferably with setting, so that user can enable/disable this autosnooze

**Comment by liroyvh** [comment]
This is a *massive* improvement. It works great so far :)

**Comment by JohanDegraeve** [comment]
ok good news
let's close the issue then ?

I didn't add a setting to let the user choose this autosnooze, I think it's a logical thing to do

**Comment by JohanDegraeve** [comment]
additional feedback 

Probleembeschrijving:
Met dev branche is het nu idd 1 alarm per 5 minuten. 
Wel een bugje: nu triggered “laag alarm” soms terwijl ik urgent laag ben. Wat er gebeurt:
- urgent laag triggered want 2.8 (ik stel in op onder 3.6 = urgent laag)
- een minuut later triggered “laag”, terwijl die pas zou moeten triggeren tussen de 3.7 en 4.2.

**Comment by liroyvh** [comment]
Currently seems to work fine, thank you!
