### ISSUE TITLE
Bluetooth windows doesn't update upon reconnection

### ISSUE THREAD

**Issue by liroyvh** [JohanDegraeve/xdripswift#199]
A very minor thing I just saw in the dev branche was that the CGM kept saying "Scanning...", whilst I was getting readings. When tapping the FSL2, it did say "Sate: Connected". Then when I tapped back, it said "Scanning..." but within a few ms this changed to "Connected" as well. It looks like the Bluetooth View had, for some reason, not updated itself once it had connected to the sensor. (Maybe it's waiting 5 minutes now before updating it? :D) 

I've tried to reproduce and it keeps happening. 
Step1: force close app
Step2: Open app and keep Bluetooth window in front
Step3: Even if its connected again, the Bluetooth window will keep claiming it's "Scanning..."
Step4: Tap the sensor, you will see it's connected. 
Step5: Go back to previous screen, you'll now see "Scanning" instantly changing to "Connected". 

For some reason, the bluetooth view won't update until you tap on the transmitter. 
I'll submit a screenrecording. 

It's by no means a major issue.

**Comment by JohanDegraeve** [comment]
I'm aware that the connect event doesn't get reported correctly. Probably an iOS issue.
Although I'm not able to reproduce, I'm using Atom, by the time I've reached the bluetooth screen the device is connected and it will show the correct status.
