### ISSUE TITLE
Some German Translation missing

### ISSUE THREAD

**Issue by Sn1kk3r5** [JohanDegraeve/xdripswift#206]
There is slightly gap of translation.

Even when the German word exists in the coding, it's still english in the App.

Some Examples from the settings screen:
Use Master or Follower
Show BG in Notifications
Show BG in the App Badge

**BG Unit got translated!**

As all translations are available I would assume the is a generic bug.

For more examples just let me know.

**Comment by JohanDegraeve** [comment]
There were some strange characters in the of the translation files 
https://github.com/JohanDegraeve/xdripswift/blob/60e33f2f466f5b0a75f2a65bbffd4016d9dee3f4/xdrip/Storyboards/de.lproj/SettingsViews.strings#L202

also an error in one of the keys

fixed in develop branch

**Comment by Sn1kk3r5** [comment]
Does it make sense for me to go through the files one more time to make some minor adjustments?

Another question: How professional do we want the translation? On some place I could create a more meaningfull discription.
Or is the target to have a basic translation, and that's all you want?

**Comment by JohanDegraeve** [comment]
yes it's ok to make additional changes

target is to translate as is, as good as possible

**Comment by Sn1kk3r5** [comment]
Got it.

Will make some changes about what I investigated in the app since the update.
