### ISSUE TITLE
mbp m1 build issue 

### ISSUE THREAD

**Issue by koll1ak** [JohanDegraeve/xdripswift#224]
Hi,
I'm using mbp m1 and currently trying to build app.
On "pod install" step facing:
anatolii@koll1ak-mbp xdripswift % pod install
Analyzing dependencies
Pre-downloading: ActionClosurable from https://github.com/takasek/ActionClosurable.git, commit a1a589cd4189768c0ac7a49da7296d95a7f4f914
/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.0/lib/ffi/library.rb:275: [BUG] Bus Error at 0x0000000101134000
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.arm64e-darwin20]

Maybe someone can help, is there any workaround?
Thanks!

**Comment by Merkaffe** [comment]
Try the command "sudo gem install ffi" before "pod install".

**Comment by koll1ak** [comment]
Thanks, that worked, but only with Terminal under Rosetta :)
I think that it would be great to add into the manual for m1:
1. Launch Terminal under Rosetta
2. Run "sudo gem install cocoapods"
3. Run "sudo gem install ffi"
4. Run "pod install"
