### ISSUE TITLE
Main screen for RTL languages

### ISSUE THREAD

**Issue by abutmim** [JohanDegraeve/xdripswift#235]
The space between (Low or High) and (>< Value) in statistics in Arabic language .  

![WhatsApp Image 2021-05-09 at 4 48 10 PM](https://user-images.githubusercontent.com/40410642/117574641-cb9d9180-b0e6-11eb-8d05-10f15623a9b0.jpeg)

**Comment by paulplant** [comment]
Fix committed https://github.com/paulplant/xdripswift/commit/e45883dab7149389aeb720dcaeae229eff3839b4 to my dev fork.

Will make a PR into Johan's develop branch in the next days.

Check added to RootViewController viewDidAppear() that checks for RTL language being used and aligns the outlets correctly.

RTL:
![Simulator Screen Shot - iPhone 12 Pro - 2021-05-11 at 21 26 18](https://user-images.githubusercontent.com/37302780/117873912-a05ea200-b2a0-11eb-9b74-2c1b99a19534.png)

LTR:
![Simulator Screen Shot - iPhone 12 Pro - 2021-05-11 at 21 27 03](https://user-images.githubusercontent.com/37302780/117873942-ac4a6400-b2a0-11eb-9f0f-f5bec01b4f32.png)

**Comment by paulplant** [comment]
#237 closed

**Comment by abutmim** [comment]
> @abutmim - can you confirm that this layout looks good?

Thanks 
Layout looks great .
