### ISSUE TITLE
[Enhancement] Confirm disconnect

### ISSUE THREAD

**Issue by liroyvh** [JohanDegraeve/xdripswift#239]
The spacing beneath the back-button (< Bluetooth) in the CGM-screen for Libre 2 Direct is very tight, therefore it is, unfortunately, not too uncommon here to accidentally tap the "Disconnect" button. It'd be nice if the app prompts you to confirm the disconnect, now it's instant.

**Comment by paulplant** [comment]
I'll check this out to work on. @liroyvh  - if I send you a test branch link, can you, build test and feedback? (I'm not using Master mode at the moment so can't test)

**Comment by liroyvh** [comment]
> I'll check this out to work on. @liroyvh  - if I send you a test branch link, can you, build test and feedback? (I'm not using Master mode at the moment so can't test)

Sure, np

**Comment by paulplant** [comment]
#242  submitted to develop branch

**Comment by paulplant** [comment]
Released in 4.6.5
