### ISSUE TITLE
Test connection doesn’t produce results

### ISSUE THREAD

**Issue by LiroyvH** [JohanDegraeve/xdripswift#247]
Was helping someone on Facebook diagnose NS issue and asked to tap "test connection". This results in... Absolutely nothing. :P So I tested it in my app and the same result: the button doesn't seem to do anything. No success or failed message or anything, nothing happens.

**Comment by paulplant** [comment]
Confirmed and marked as bug

**Comment by LiroyvH** [comment]
To add on to this one: error handling might be a good idea too. I had accidentally let my SSL Certificate expire and apparently XDrip checks aggressively on that. Which is a good thing, but then it'd be nice if the app produces an error saying a secured connection with nightscout cannot be established for <reason>, such as a self-signed or expired certificate. 

Re-signed the cert and its all happy now.
