### ISSUE TITLE
since new update a ton of missed readings libre 2 direct

### ISSUE THREAD

**Issue by KevinDenys** [JohanDegraeve/xdripswift#252]
Since the new update (4.6.6 - 4161) I'm having a lot of missed readings. When I open the app it starts working again for a few hours. I have the phone with me the whole day. Did something change in the last update? Also on the facebook group there are a lot more posts about people having missed readings. (could also be cause more people are using xdrip4ios because of the tomato app not working)

**Comment by JohanDegraeve** [comment]
Nothing changed.

**Comment by KevinDenys** [comment]
Thank you for the information.

**Comment by wiegerthefarmer** [comment]
@KevinDenys were you able to figure anything out? I'm getting missed readings as well.
