### ISSUE TITLE
[feature] local data export

### ISSUE THREAD

**Issue by KevinDenys** [JohanDegraeve/xdripswift#253]
Is there a way of exporting the current local data (last 90 day data) as a csv? If not why not? I mean the data is there on the device. Just exporting it as an csv would be a great but small feature to implement. Is there a reason no to do this?

**Comment by JohanDegraeve** [comment]
It's a matter of time and priorities, the effort spent in the project is very limited the last few weeks or even months

**Comment by KevinDenys** [comment]
but it would be possible? its not restricted by apple or other things. Time that I learn some swift and implement it :D Thank you for doing godswork!

**Comment by m-a-v** [comment]
@KevinDenys You could upload your data to Nightscout and then export it.

**Comment by KevinDenys** [comment]
@m-a-v I know but that requires setting up a nightscout server. I was just wondering if it was possible cause xdrip has all the data allready stored locally on the device. I have apple healthcare upload enabled and that allows me to receive the csvs (just extra work)

**Comment by JohanDegraeve** [comment]
> but it would be possible? its not restricted by apple or other things. Time that I learn some swift and implement it :D Thank you for doing godswork!

there' s no Apple restriction, you just need to create a file then give options to share that file

Indeed time you learn some Swift :)

**Comment by StevenWillett** [comment]
+1 for this feature.

**Comment by noah-fl** [comment]
eventually this will be available soon, see https://github.com/JohanDegraeve/xdripswift/pull/271

**Comment by KevinDenys** [comment]
Closing this issue cause of https://github.com/JohanDegraeve/xdripswift/releases/tag/4.10.3 "DataExporter"
