### ISSUE TITLE
Development MacBook Air M1

### ISSUE THREAD

**Issue by florisi** [JohanDegraeve/xdripswift#254]
I've tried to run 'pod install' but it crashes.
Anything I can do about it.
Running op an MacBook Air with M1 chip.

**Comment by LiroyvH** [comment]
@florisi 
What exactly is the full output of that command including the errors?

**Comment by IJdacolet** [comment]
I've solved it. I should run Terminal "Open with Rosetta".
That did the job.

**Comment by florisi** [comment]
I solved it. I should run Terminal "Open with Rosetta".
That did the job.

**Comment by paulplant** [comment]
Great. We'll get the documentation updated with the M1 specific build instructions. I'll close this issue
