### ISSUE TITLE
Libre algorithm doesn’t populate nightscout RAW-value

### ISSUE THREAD

**Issue by LiroyvH** [JohanDegraeve/xdripswift#262]
When using any of the calibrated options, xDrip4iOS will properly populate the RAW-value sent to nightscout. When using the Libre Algorithm, however, xDrip4iOS will upload a RAW-value of null/0 to Nightscout. 

Whilst the following is absolutely not your problem, I hope it can be solved regardless: this causes issues with NS-predictions and also for Spike which seems to choke on it and expects a raw-value to keep proper track of all its values and predictions plus it doesn't update the initial on-boot value it obtains, as it doesn't see 0.00 as an update to 0.00 and thus will believe it is missing readings. It can in edge cases, notably when someone has left Spike running for a while in this state, unfortunately also cause (dangerous) issues with the bolus calculator. Spike will always go to its double-arrow status (unknown Delta/Trend) and refuse to read further until it is restarted and picks up a fresh regular value; but choke again on the 0 raw value. 

I'm not 100% confident this problem is caused by the RAW-value being empty, but after a lot of testing and trying to exclude things: this is the only difference I, admittedly with limited background knowledge, can find. (Although I also found it suspicious Spike can't determine a trend from Libre Algorithm uploads; but that might be tied to RAW.) It works fine with XDrip in calibrated mode, but instantly dies on Libre Algorithm; and only difference seems to be RAW-value not getting properly populated with Libre Algorithm. 

To exclude and hopefully to fix this problem, it'd be really nice if xdrip4ios can copy the BG-value it measures in to the RAW-value and upload both to Nightscout. As always, I'd be happy to testdrive any proposed changes. :) 

Thanks for your consideration :)

**Comment by BaQs** [comment]
let me +1 this case. Have you managed to follow up ? maybe post an issue on xdrip4io5 ?
does spike support FSL2 as source and could be a master ?

**Comment by JohanDegraeve** [comment]
do I understand correctly that you want the field "filtered" and "unfiltered" to be filled in and set equal valua as sgv ?

**Comment by BaQs** [comment]
hello,

to be honest I don't know.

I think, like @LiroyvH , I use a combination of:
1. xdrip4io5 as a master, using libre algorithm
2. Spike app as a follower. Spike does not update. Only once at start. Spike then does not offer prediction either.

in this configuration, it seems @LiroyvH identified the issue in his first post. I confirm when setting calibration (instead of libre algorithm) everything works fine. 

If you want me to try a specific version, please don't hesitate to ask ;)

**Comment by JohanDegraeve** [comment]
can you try this branch ? https://github.com/JohanDegraeve/xdripswift/commits/fix-262

**Comment by BaQs** [comment]
woh, let me setup xcode env then :)

any way to test this specific branch via testflight ?
OR: if you have an .ipa, I can try to sideload it & test.

**Comment by JohanDegraeve** [comment]
if you give me your apple account email address (you can send it to xdrip@proximus.be) I'll add you as App Store Connect user, you will then be able to test new releases in TestFlight, without having to wait for the review by Apple.
I can make a release for that

**Comment by BaQs** [comment]
doing

**Comment by BaQs** [comment]
so, I confirm the 4.7.3 works \o/

A big big thanks!

**Comment by m-a-v** [comment]
Thanks for the code changes and testing. That was on my todo list.

Thanks also for @LiroyvH for finding out the differences.
