### ISSUE TITLE
Make tapping “home” return to latest reading

### ISSUE THREAD

**Issue by LiroyvH** [JohanDegraeve/xdripswift#263]
You can scroll back in history. If you have to scroll quite a bit back, let's say a month, that's quite a few taps. But you also have to scroll all the way back to get back to the current value as there's no way (that I could find) that'll make it return there; other than fully restarting the app.

Making it return back to recent by tapping home might be a nice enhancement, also for people, notably new users, whom have accidentally scrolled back and don't understand what's going on. They'll probably ram the home button at some point to try and fix it :P

**Comment by JohanDegraeve** [comment]
return to latest reading is done by double tapping on the graph
