### ISSUE TITLE
No such module 'ActionClosurable'

### ISSUE THREAD

**Issue by becksen** [JohanDegraeve/xdripswift#265]
During Compiling I get the following error. The import is not successful.

**Comment by LiroyvH** [comment]
Install the pods like the guide says

**Comment by becksen** [comment]
I did install Cocoapods in order to resolve dependencies. Nevertheless when I try to compile the app I get the error. Even if I comment the line other errors will occur. Not sure what else can be done.

**Comment by becksen** [comment]
I've reviewed all steps. I've found one comment in the docs https://xdrip4ios.readthedocs.io/en/latest/install/build/ regarding Apple M1 processor. Unfortunately the paragraph is not completed. Hence there is no details what to consider in case using M1 processor. Can you help which steps are required in addition?

Regards.

**Comment by paulplant** [comment]
@becksen Can you try to locate Terminal in Finder -> Applications, then right click the icon and select Get Info. Enable "Open using Rosetta".

Then launch Terminal again, navigate to the build folder and try and re-run "pod install" command.

Please feedback if this works for you and I'll get the documentation updated with this solution.

**Comment by becksen** [comment]
@paulplant 
Thanks for the feedback. The "open using Rosetta" checkbox itself is not sufficient. I've completed those steps to successfully compile xdrip4ios on M1 MacBook Pro.

- cloned terminal app and activated "Open using Rosetta" <img width="299" alt="image" src="https://user-images.githubusercontent.com/10520069/133495998-a7bc8036-cb38-4573-b9df-a5e47eb2a7c2.png">
- uninstalled cocoapods: `sudo gem uninstall cocoapods`
- acitvate foreign function interface: sudo gem install ffi -- --enable-system-libffi
- install cocoapods: sudo gem install cocoapods
- continue the instructions with https://xdrip4ios.readthedocs.io/en/latest/install/build/: pod install
Thanks.

**Comment by paulplant** [comment]
Aha! Now I remember. I also had to install ffi for my M1 Macbook but couldn't remember what steps I did when I wrote the guide.

With your permission I'll close this issue here (as it isn't strictly an issue with xdripswift) and I'll push an update to include your instructions in the documentation tomorrow 👍
