### ISSUE TITLE
Edited

### ISSUE THREAD

**Issue by gui-dos** [JohanDegraeve/xdripswift#270]
Edited

**Comment by JohanDegraeve** [comment]
i will add a logging of the rawtemperature value, to see if that matches 0 values
Do you want to see this error code processed ?
0 values are skipped always

**Comment by gui-dos** [comment]
It was confirmed by @keencave on https://gitter.im/LibreOOPAlgorithm/Lobby that this is part of the firmware: it's the sensor way to communicate error codes among the stream of glucose values.

There is usually only one `0x20` code and it is tied to a specific wear time: it was while observing it appearing and disappearing during the first minutes and than vanishing definitely after 15 minutes that I discovered on my own that the Libre 2 doesn't send the latest seven trend values but those at the indexes `[0, 2, 4, 6, 7, 12, 15]`.
