### ISSUE TITLE
Unable to install "xdrip"

### ISSUE THREAD

**Issue by afrikanov** [JohanDegraeve/xdripswift#281]
Hi everybody! I follow the instruction, paste bundle identifiers for all targets, launch app on device (iPhone 12), it builds successfully, but the error "Unable to install "xdrip" appears. 

Details

Unable to install "xdrip"
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402652985
--
A WatchKit app within this app is not a valid bundle.
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402652985

 Can anyone help, please? :)
@JohanDegraeve 
@JtxGit
@gui-dos

**Comment by LiroyvH** [comment]
Please don't randomly tag people. Also, this is by far not enough details to make any conclusive statement about what is going wrong for you, you've left out a lot of output.

However, based on past encounters: I'm assuming you're using a free Apple ID, no Apple dev membership?

**Comment by afrikanov** [comment]
Of course I have dev membership. 
1) No
2) No

I removed code for Apple Watch and project was build successfully. Are there any Apple Watch incompatibilities ?

**Comment by paulplant** [comment]
If you pasted Bundle Identifiers, then this is why it failed.

You need to follow the online build documentation unless you know how to manually edit and make compatible different extensions and targets:

https://xdrip4ios.readthedocs.io/en/latest/install/build/

The error you described can *only* happen when you didn't correctly set xDripConfigOverride.xcconfig following the above instructions.
