### ISSUE TITLE
Error installing program

### ISSUE THREAD

**Issue by lantus1902** [JohanDegraeve/xdripswift#285]
An error occurred while compiling the program 
Showing All Messages
Unable to load contents of file list: '/Target Support Files/Pods-xdrip/Pods-xdrip-frameworks-Debug-input-files.xcfilelist'

What shall I do? How to work around this error?

**Comment by JohanDegraeve** [comment]
did you check the documentation?
https://xdrip4ios.readthedocs.io/en/latest/

**Comment by paulplant** [comment]
Please follow the official build instructions:

https://xdrip4ios.readthedocs.io/en/latest/install/build/

Closing this issue as it is a user-specific build problem and not related to the project.
