### ISSUE TITLE
Instal error

### ISSUE THREAD

**Issue by koll1ak** [JohanDegraeve/xdripswift#287]
Hi,
Facing issue on installing application 

This app contains an app extension with an illegal bundle identifier. App extension bundle identifiers must have a prefix consisting of their containing application's bundle identifier followed by a '.'.
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402653026

Works perfectly on simulator, but running on error on real device.
Devices:
MBP m1
iPhone 12
AppleWatch 6

**Comment by JohanDegraeve** [comment]
did you check the documentation?
https://xdrip4ios.readthedocs.io/en/latest/

**Comment by koll1ak** [comment]
Hi John, 
Thanks for the link. I double-checked all manipulations with the override file but still see this error.

**Comment by jonisaksson** [comment]
You are probably better posting any issues on the facebook group than here.

**Comment by paulplant** [comment]
Closing issue as this is a user-specific build error, it isn't related to the project. Please feel free to join the Facebook group for one-on-one build help.
