### ISSUE TITLE
Error during the Installation from source code

### ISSUE THREAD

**Issue by whynot2018** [JohanDegraeve/xdripswift#288]
Hi
It gives an error under xcode when I try to install as an Apple Developer account.
`Errors were encountered while preparing your device for development. Please check the Devices and Simulators Window. 
<none> Cancel Running`
![error](https://user-images.githubusercontent.com/48062504/145686663-bb20e668-2e45-4f08-b475-5a221235bc56.png)

**Comment by paulplant** [comment]
I'll close this as it is a git clone or Xcode build issue and not related to the xdripswift project. The instructions in the online documentation are valid and work. Please ensure that Xcode is always kept updated to prevent issues with an updated target device:

https://xdrip4ios.readthedocs.io/en/latest/install/build/
