### ISSUE TITLE
Auto update of XDrip4iO5 beta does not function when traveling?

### ISSUE THREAD

**Issue by Ericpv** [JohanDegraeve/xdripswift#295]
![D86F3269-3348-4BE0-9B23-0861982C4C26](https://user-images.githubusercontent.com/96672103/147397704-3753f100-cf0e-4d24-830d-bcfc4b881308.png)
![175D8075-FC69-4881-8939-7152D4F31EDC](https://user-images.githubusercontent.com/96672103/147397707-22a93857-99ec-4789-9abf-a8683971e2be.png)

hi I’m currently in UK (usually based in USA, where I downloaded and have come to rely on the beta) and received the “beta has expired” prompt when opening XDrip4iO5.   TestFlight insists I have no betas to update.   But XDrip4iO5 has been auto-updating since installation.   Is this somehow connected to use of non-USA servers whilst roaming, or something else?   Will the beta function again when I return to USA?   And how do I switch off alarms if the beta has expired?

**Comment by Jonnovandereng** [comment]
Hi, I have the same problem.

**Comment by quotengrote** [comment]
Nope, the beta is full. happens here too. Only thing i am wondering is why it wouldn't work for existing beta users.

**Comment by Ericpv** [comment]
“Missed readings” alarm is going off every 30 minutes but I can’t access app to switch it off.   Don’t want to delete app as the beta is full and I probably won’t be able to reinstall.   This is both annoying and alarming.   Have I just been chucked out?

**Comment by quotengrote** [comment]
Deactivate the messages in the system-settings per app.

**Comment by JohanDegraeve** [comment]
indeed that's the best solution : disable notifications for the app in your ios settings

**Comment by Ericpv** [comment]
Thanks - I’ve never understood IOS but that’s sensible!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by quotengrote** [comment]
> indeed that's the best solution : disable notifications for the app in your ios settings

Hi John,

do you know what the Problem with the beta is? Was my guess correct? And if so, is there another way besides building from source?

Greetings
mg
