### ISSUE TITLE
App crash when toggling between master and follower mode - iPhone X

### ISSUE THREAD

**Issue by JohanDegraeve** [JohanDegraeve/xdripswift#3]
Reported by one user
iPhone X with iOS 12.3.1
App version 2.0.14

anyone who has the same problem ?

**Comment by m-a-v** [comment]
I can reproduce it.

Initiale situation: master mode active, Nightscout enabled, I have no transmitter connected

1) disable Nightscout
2) change to Follower
3) tap again on Follower => crash

**Comment by JohanDegraeve** [comment]
Commit 5205253a9d2243a5f477b62bad77b52edaeeac5f
Not sure however if this fixes the problem.
NightScout upload was being triggered when setting on follower mode, which is not the aim.
Also other fixes related to settings that are disabled.
And removed also the automatich enabling of NightScout when switching to follower. I plan to add an info button later which will explain that NightScout needs to be enabled, in stead of doing it automatically
