### ISSUE TITLE
Crash after input of nightscout URL

### ISSUE THREAD

**Issue by OliNix** [JohanDegraeve/xdripswift#300]
After inputting a NightScout URL, the app will crash and close.

Restart of the app and enter of secret key works ok and no crashes after.

It only crashes after you initially input your nightscout URL.

**Comment by paulplant** [comment]
Did this happen to you, or one of the users on your Testflight?

We'd need to get the logs sent via the "Send Issue Report" option in the Settings menu shortly after this happened (or at least telling us exactly what time if happened).

Also, if it was somebody on your Testflight, did they send crash feedback to you? If so, forward this to us also please.

I had somebody mention this to me on the 28th but I was unable to reproduce the issue using their URL.

**Comment by OliNix** [comment]
I had this happen to myself, 3 days ago.

How do I capture the crash log?

**Comment by paulplant** [comment]
If it were 3 days ago it is likely purged from the trace file but you can try it anyway... just hit Send Issue Report from the settings menu and write "NS URL crash 3 days ago" in the e-mail title.

The crash logs are a different thing sent via Testflight and can only be sent to the app releaser/developer at the time it happens.

**Comment by OliNix** [comment]
I can repeat it on demand. I have just repeated the crash and sent the trace log to you.

I have also submitted the crash log to myself. How can I export from TestFlight?

**Comment by paulplant** [comment]
There's nothing in the trace files that helps unfortunately (which kind of makes sense if it provokes a fatal error before it can write to the file).

I'm not sure about exporting from TF... (@JohanDegraeve - any ideas?)

If you are able to see the crash report, does it give an idea of where/what crashed? I'm not sure if you can copy/paste anything here? Or a screenshot?

**Comment by OliNix** [comment]
> There's nothing in the trace files that helps unfortunately (which kind of makes sense if it provokes a fatal error before it can write to the file).
> 
> 
> 
> I'm not sure about exporting from TF... (@JohanDegraeve - any ideas?)
> 
> 
> 
> If you are able to see the crash report, does it give an idea of where/what crashed? I'm not sure if you can copy/paste anything here? Or a screenshot?

I will take a look. See screen recording of crash:

https://user-images.githubusercontent.com/16334811/147778187-874a0520-5c55-40ed-bc3e-86335015bb3a.MOV

**Comment by paulplant** [comment]
OK, but this isn't what you opened the issue for 😅... The issue was crashing on entering a URL but in the video it only crashes when you delete the URL (leaving the API_SECRET in place) and hit enter. Adding the URL initially doesn't actually crash the app.

This helps a lot actually... I'll look at it tomorrow and we'll push out a fix.

**Comment by paulplant** [comment]
Issue reproduced and I have an idea what it is. I'll fix tomorrow and PR to develop branch.

**Comment by OliNix** [comment]
> OK, but this isn't what you opened the issue for 😅... The issue was crashing on entering a URL but in the video it only crashes when you delete the URL (leaving the API_SECRET in place) and hit enter. Adding the URL initially doesn't actually crash the app.
> 
> 
> 
> This helps a lot actually... I'll look at it tomorrow and we'll push out a fix.
> 
> 

Yes, appears I can only recreate on delete now. When I push a new build I will try and capture logs for if it happens on entry.

> Issue reproduced and I have an idea what it is. I'll fix tomorrow and PR to develop branch.

I have exported the TF log also:
[](https://www.icloud.com/iclouddrive/03bDzd8y8uwJW0eDc6sGhvRBQ#NS_URL_Delete_Crash_TFEXPORT)

**Comment by paulplant** [comment]
No worries. I've caught it (and should have spotted it when I made the changes)

<img width="952" alt="image" src="https://user-images.githubusercontent.com/37302780/147779408-052460da-d81a-4e42-bbc3-be44153556df.png">

Fixed ;)

**Comment by JohanDegraeve** [comment]
lessen learned : never use force unwrap :)

**Comment by JohanDegraeve** [comment]
> How do I capture the crash log?

log on to appstoreconnect, select the app, testflight, crashes
you see a list of crashes, open yours
dowload the crash log and open

here you see where it crashes (this is from a user that uses my testflight account)
<img width="1276" alt="Schermafbeelding 2021-12-30 om 23 28 36" src="https://user-images.githubusercontent.com/13840461/147791998-7675332b-6a77-4d11-961f-d11ac738868b.png">

**Comment by OliNix** [comment]
> 
> 
> > How do I capture the crash log?
> 
> 
> 
> log on to appstoreconnect, select the app, testflight, crashes
> 
> you see a list of crashes, open yours
> 
> dowload the crash log and open
> 
> 
> 
> here you see where it crashes (this is from a user that uses my testflight account)
> 
> <img width="1276" alt="Schermafbeelding 2021-12-30 om 23 28 36" src="https://user-images.githubusercontent.com/13840461/147791998-7675332b-6a77-4d11-961f-d11ac738868b.png">
> 
> 
> 
> 
> 
> 

Thanks Johan. I linked the whole .zip file above, but this is good to know for future reference.
