### ISSUE TITLE
Alerts do not work if Override Mute is disabled

### ISSUE THREAD

**Issue by OliNix** [JohanDegraeve/xdripswift#301]
Tested on iPhone XS (iOS 15.2) with Apple Watch S5 (WatchOS 8.3) connected.

When Override Mute is ENABLED for an alert, the volume of the alert changes with iPhone volume.

When Override Mute is DISABLED for an alert, no alert sounds at all even when iPhone is not muted. When “Test Volume (Current iPhone Volume)” is selected, no sound is played. iPhone volume is set to 50%.
![62F013A1-CCF1-4CD2-952E-1F4B55F4D9F1](https://user-images.githubusercontent.com/16334811/147752121-4328fc92-f367-4c56-b912-aadb83911f06.jpeg)

**Comment by neirfeno** [comment]
Experiencing this also, which is frustrating as it means there’s effectively no alarms (a silent alarm isn’t an alarm)

**Comment by LJWatson** [comment]
Confirmed on an iPhone 12 Mini running iOS 15.1.1.

**Comment by OliNix** [comment]
Issue still occurs in v4.10.1

**Comment by OliNix** [comment]
Not a bug #429 addresses the issue correctly.

This occurs if an Apple Watch is connected. Issue can be closed
