### ISSUE TITLE
RFC: Grab Nightscout data and display it in the App

### ISSUE THREAD

**Issue by sefagmbck** [JohanDegraeve/xdripswift#306]
This is the first time I ask for a feature request, so please tell me if I did it in a wrong manner.

I just went from using Spike to xDrip. You have done an amazing job with the app!

Feature wish:
I think it would be really nice if it was possible to read bolus, basal entires, IOB from Nightscout and then fetch it into the glucose line in the app? 

Why:
If you are a "looper" then you will get a really good overview of the current status, especially if you are a follower. 

Thanks once again for an amazing app.

Br
Mathias

**Comment by JohanDegraeve** [comment]
There's development going on to create treatments in xdrip4ios.
My plan is to add syncing with NS : which means up and download treatments

basal entries is not yet in scope.

it should be possible to calculate IOB on xdrip4ios, although that's also not yet in scope, but I think this will quickly follow

**Comment by tromanisagit** [comment]
Hi

Just some comments. 

Having the ability to read and post to Nightscout treatments would be great. 
Also to apple health again both read and write.  
How much to store local? Maybe apple health is the answer to local offline storage anyway.  
Iob offline of huge value as there are limited apps that do this and having it on one screen without the need for internet would great.  

I'll build the branch and help test if you want?

**Comment by JohanDegraeve** [comment]
Hi,

development is ongoing, there's. treatments branch

regards,

johan

**Comment by paulplant** [comment]
Bolus and carb treatments are now implemented in 4.10.0 with full Nighscout syncing for both master and follower modes.

Further improvements/additions will likely come, but I'll close this issue as resolved for now.
