### ISSUE TITLE
XDrip as follower doesn't work

### ISSUE THREAD

**Issue by IJdacolet** [JohanDegraeve/xdripswift#308]
I have a working configuration for my girlfriend with xdrip and Nightscout (via herokuapp).
When I install xdrip on my iPhone and set it up as follower I don't get any values.

A test to Nightscout on my iPhone(test connection) is successful.
So I don't know what else to do.

**Comment by paulplant** [comment]
xDrip4iOS is working fine as a Nightscout follower. Please give more details.

For general technical support with the app, please join the Facebook group: https://www.facebook.com/groups/853994615056838

If you have followed all instructions and are sure that this is a fault, please contact us at xdrip@proximus.be with screenshots of your Nightscout URL within the app and also your API_SECRET or readable Token for us to troubleshoot.

I'm going to close this as it isn't a specific issue with the app. If you can send confirm and send further details, we can re-open if necessary. Thanks!
