### ISSUE TITLE
Interval not working with libre 2 direct

### ISSUE THREAD

**Issue by miguelpruivo** [JohanDegraeve/xdripswift#314]
Hi. I've set the interval to 3 minutes with libre 2 direct but I'm still getting readings every minute. Already tried to restart the app but doesn't seem to produce any effect.

**Comment by JohanDegraeve** [comment]
Libre 2 sends a new reading every minute to xdrip4ios. That interval can not be changed.
When you change the interval in the xdrip4ios settings, you only change the interval of the notification.
If you look at the home screen, you will see that it continues to update the reading every minute, if you would use M5Stack with bluetooth connection, then you would see it continues to update the reading every minute

**Comment by g7kbr** [comment]
Hi John

with this issue, say if you are using andriodaps the data in sayiny duplicate readings and is shown in red.  Or does andriod xdrip resolve this issue?  I am currently looking at moving onto andriodaps 3 using libre 2 with OOPS2.  Currently using freeaps and  xdrip4dos.
