### ISSUE TITLE
data refresh rate in follower mode delayed

### ISSUE THREAD

**Issue by rzahnpu10** [JohanDegraeve/xdripswift#327]
Thank you for this project.  I just started using this app and found a possible bug.  Hopefully this is the format you are looking for.  Model: iPhone 12 
iOS: 15.2.1

I have the app configured as a follower to read from nightscout. 

Ive noticed that the data is always 5+ minutes old.  Compared to the nightscout webpage or the Dexcom Follower application.
essentially, i am only seeing the last read time anywhere from 5-10 minutes old.  I have another possible bug report that may be related to this pertaining to the app badge.  I have a feeling that the delay in the data pull is causing the app badge to not be displayed because of the "stale" data.  If i force close the application and reopen, it will grab the most recent data from nightscout with the delta typically being 0-4 minutes.  At this point the app badge displays properly until the delay reaches over 5 minutes.

If you need anymore information please let me know.  Happy to help.

Thanks!

**Comment by rzahnpu10** [comment]
just saw you release 4.9.2 a few hours ago.  I have 4.9.1 installed.  Let me try that version as i see it mentions follower improvements.

**Comment by rzahnpu10** [comment]
Upgraded to 4.9.2.  Upon opening the app, the time delta was 0 minutes and the glucose reading was the expected value.  however, as i left it open it slowly crept its way up to 10 minutes.  After hitting 10 minutes, it read in the next value and the delta went back to 5 minutes while also showing the glucose value from the same 5 minute time frame.  hopefully that is helpful.

**Comment by bjornoleh** [comment]
I have noticed the same. 

I suspect some improvements along the lines of https://github.com/nightscout/cgm-remote-monitor/pull/7231 could fix this.

**Comment by paulplant** [comment]
This happens when we set the future timer (based upon the timestamp of the last received glucose value) and for some reason it doesn't get triggered or NS doesn't respond in time, it then waits for the next one.

I've used a test version with the NS polling increased from every 5 minutes to every minute just to see if it impacts battery life and it seemed to be fine.

Maybe we could add an option for "Aggressive NS Polling" for Followers. 

We'll look into it. In my tests, this worked fine to keep the lags below 6 minutes.

**Comment by paulplant** [comment]
The follower performance should be greatly improved in the next release (currently in develop branch).

**Comment by bjornoleh** [comment]
Thanks, testing now, looks good so far.

lør. 30. apr. 2022 kl. 20:44 skrev Paul Plant ***@***.***>:

**Comment by paulplant** [comment]
I'll close this issue as it should be solved after the 4.10.0 release.
