### ISSUE TITLE
Dexcom Share upload is broken

### ISSUE THREAD

**Issue by bjornoleh** [JohanDegraeve/xdripswift#328]
Upload to Dexcom Share is not working in v4.9.1 (and likely not in v4.9.2 either). 
Tested with Dexcom G6 in xdripswift 4.9.1 on iOS 13.3.

Dexcom changed the format of the `trend` data at the end of 2021, first in EU region (OUS), then in the US region too. This is likely the cause of the issue. The data were changed from integer values, into strings:

`"DoubleUp", "SingleUp", "FortyFiveUp", "Flat", "FortyFiveDown", "SingleDown", "DoubleDown", "NotComputable", "RateOutOfRange"`

More info here: https://github.com/LoopKit/Loop/issues/1576

And here is a commit to fix the issue in LoopKit dexcom-share-client-swift: 
https://github.com/LoopKit/dexcom-share-client-swift/commit/1faf69fdd1ceb8e174f53be16214a8d3559bb081

// Dec 2021, Dexcom Share modified json encoding of Trend from int to string
                                let trendmap = ["": 0, "DoubleUp":1, "SingleUp":2, "FortyFiveUp":3, "Flat":4, "FortyFiveDown":5, "SingleDown":6, "DoubleDown": 7, "NotComputable":8, "RateOutOfRange":9]

**Comment by bjornoleh** [comment]
Any chance for someone to have a look at this?

We are alternating between Xdrip4iOS and the Dexcom app with overlapping transmitters to be able to do uninterrupted looping. This is a great improvement in quality of life, since the erratic readings during the first 24 hours happens in the background. But we do miss the Dexcom share option in Xdrip. Currently using FreeAPS to upload to NS, but this is unfortunately a little spotty. 

I hope and believe the fix is pretty easy, judging by the changes required to fix other apps that got broken due to the changes in Share data format before Christmas. 

Fingers crossed!

**Comment by bjornoleh** [comment]
Thanks for taking a look @JohanDegraeve !

I really don't know. Your changes look reasonable if I understand this correctly. It seems you set the slopeOrdinal by evaluating the slope, and then pick the correct trend string? 

xdripswift/xdrip/Core Data/classes/BgReading+CoreDataClass.swift:    func slopeOrdinal() -> Int {

I do notice you seem to miss "RateOutOfRange":9 ( I guess "NotComputable":8, is covered by the "default: "NotComputable" "? )

We will change to Xdrip4iOS in the next couple of days (have a sensor on Dexcom app now). Can test more then.

Should I be able to see the output in debug when plugged in to Xcode?

Here are the major changes in Xdrip+ related to the ransition from trend as integer to string, perhaps something useful here? I believe upload to Share works in Xdrip+, but havent checked:
https://github.com/NightscoutFoundation/xDrip/pull/1885/files

**Comment by JohanDegraeve** [comment]
> I do notice you seem to miss "RateOutOfRange":9 ( I guess "NotComputable":8, is covered by the "default: "NotComputable" "? )
> 
My original code only gives int values  0 to 7. In the change here those values are mapped to a string, default to NotComputable

**Comment by JohanDegraeve** [comment]
> Should I be able to see the output in debug when plugged in to Xcode?
Yes if you enable NSLog in the developer settings (in the app)  and also "include debug level" in the problem report settings
If you install Apple 2 configurator, then connect your iphone to your mac, enable the two settings,
then in A terminal session type:
/Applications/Apple\ Configurator\ 2.app/Contents/MacOS/cfgutil syslog | grep --line-buffered DexcomShareUploadManager | awk -F "4175 " '{print $2}'
Then you can also see all logs, specific related to Dexcom upload
> 
> Here are the major changes in Xdrip+ related to the ransition from trend as integer to string, perhaps something useful here? I believe upload to Share works in Xdrip+, but havent checked: https://github.com/NightscoutFoundation/xDrip/pull/1885/files
I don't see what else to do actually

**Comment by bjornoleh** [comment]
Ok, thanks for looking!

I’ll try with the debugger once we get the next sensor going in a day or two.

**Comment by JohanDegraeve** [comment]
forgot to mention, if you use the Apple 2 configurator tool (cfgutil), in the example I gave you should note the app version, in this example it's 4175 (you can see that version also in the settings)

**Comment by bjornoleh** [comment]
I didn't quite get the syslog grep to work. Should I do this while in Xcode debug mode, or not? Either way, here is the Terminal output:

```
% /Applications/Apple\ Configurator\ 2.app/Contents/MacOS/cfgutil syslog | grep --line-buffered DexcomShareUploadManager | awk -F "4175 " '{print $2}'
objc[85349]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x7ff946c47f90) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10e15ff90). One of the two will be used. Which one is undefined.
objc[85349]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x7ff946c47fe0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10e15ffe0). One of the two will be used. Which one is undefined.
```

Ah, logs are coming in now:
`DexcomShareUploadManager       22:07:55 in upload, dexcomShareSerialNumber or dexcomShareAccountName or dexcomSharePassword is nil`

The same logs are visible in Xcode, by the way. Looks like the login is not sa expected? In the Xdrip app, there was a dialogue stating that the login was successful.

**Comment by JohanDegraeve** [comment]
did you set a receiver serial number


> I have tested getting data into NS via bridge, this is not working (unsurprising with the logs).

what exactly did you try?

**Comment by bjornoleh** [comment]
I did not test using a receiver s/n. 

I have a NS site set to receive data from this Dexcom account using Share / NS bridge. No data arrived. This was working earlier today when using the Dexcom G6 app

**Comment by bjornoleh** [comment]
> 
@JohanDegraeve 
I just dug out a receiver, will test with the  S/N added to the settings. I don’t suppose there is any need for the receiver to be connected to the active transmitter?

**Comment by bjornoleh** [comment]
Oh, great news! I just tested with the s/n, and the Share upload works! Confirmed by getting the data into NS via bridge, and into Loop Follow. I wish I knew to try this the first time!

My testing now was with the latest released version of Xdrip Swift, so without the changes in https://github.com/JohanDegraeve/xdripswift/commit/695032836781e923aa3160ea9b3a955fc9b37332

To my surprise, trend arrows are displayed correctly in NS too, so perhaps no need for those changes? 

Should I test those as well?

**Comment by JohanDegraeve** [comment]
you mean test the trend arrows in NS?

so the issue can be closed without merging this commit?

**Comment by bjornoleh** [comment]
> you mean test the trend arrows in NS?
> 
> so the issue can be closed without merging this commit?

Yes, I tested without that commit, and the trend arrows seem fine without. 

I could test that commit as well if you like.

**Comment by bjornoleh** [comment]
Would any receiver be valid? Or would it have to be linked to the Dexcom account? I might have done something like that, can’t quite remember since it would have been two years ago. Perhaps these are some details for the docs that should be collected.

**Comment by JohanDegraeve** [comment]
not necessary to test the change
just close the issue

**Comment by JohanDegraeve** [comment]
> Would any receiver be valid? Or would it have to be linked to the Dexcom account? I might have done something like that, can’t quite remember since it would have been two years ago. Perhaps these are some details for the docs that should be collected.

I think any receiver is ok

**Comment by bjornoleh** [comment]
> > Would any receiver be valid? Or would it have to be linked to the Dexcom account? I might have done something like that, can’t quite remember since it would have been two years ago. Perhaps these are some details for the docs that should be collected.
> 
> I think any receiver is ok

Confirmed, I tested now with the S/N of a second receiver that has not previously been associated with this Dexcom account. 

Thanks for the support, and sorry for not testing this sooner. I’ll see if there is an obvious place in the docs to put this info, I don’t think it’s mentioned. 

I’ll close the issue with this remark.
