### ISSUE TITLE
Dexcom G6 transmitter days -1

### ISSUE THREAD

**Issue by diabetlum** [JohanDegraeve/xdripswift#333]
hi
I have an 8SBXXX Serie Dexcom G6 transmitter. Where did Transmitter days go? Is this a bug?
And I have an old transmitter 812XXX with firmware 1.6.5.25. Can we do the hard reset transmitter under xdripswift?
![dexcom_8SB](https://user-images.githubusercontent.com/44998140/158878459-cb2b1c5b-0ed5-44a2-8537-67d7dec47663.jpeg)
Thanks.

**Comment by LiroyvH** [comment]
Yeah the runtime -1 is a bug. You can see the transmitter start date & time above there though.

**Comment by diabetlum** [comment]
it can't be the same as the sensor start time. It should be something like 40 days.

**Comment by diabetlum** [comment]
Yes, you are right Transmitter start time is correct. But I think Transmitter Runtime should be over 40 days. Actually, what is that Battery Runtime? Transmitter activation time (days)? By the way, I tried a different sensor and transmitter they are also the same. Sensor time should be 10.03.2022 and transmitter time is but correct 12.03.2022
![ss](https://user-images.githubusercontent.com/44998140/158977871-2377242e-47c7-4401-90ce-b23cb51f6c76.jpeg)
.

**Comment by diabetlum** [comment]
Yes, you are right. I thought Battery runtime is transmitter activation days. Right now I started to use a different transmitter 812XXX with the same sensor.
![swift](https://user-images.githubusercontent.com/44998140/159166232-e980a8b6-75b1-4823-b142-9bae7f5a0753.jpeg)
Thank you.

**Comment by alphastrem** [comment]
Well I fancied a trip to the sun…
[cid:D4A0EBDC-FA19-4AA2-B6BD-A8D72D4EF5BA-L0-001]


On 20 Mar 2022, at 10:04, Diabetlum ***@***.***> wrote:

﻿

Yes, you are right. I thought Battery runtime is transmitter activation days. Right now I started to use a different transmitter 812XXX with the same sensor.
[swift]<https://user-images.githubusercontent.com/44998140/159166232-e980a8b6-75b1-4823-b142-9bae7f5a0753.jpeg>
Thank you.
