### ISSUE TITLE
Libre Pro Support

### ISSUE THREAD

**Issue by prakashdevadas69** [JohanDegraeve/xdripswift#338]
Hi,
We need your help in providing support on xDrip4ios for Libre pro sensor with Miao 3. 
Recently  Libre pro support has been provided on xdrip for Android and is working fine.
It would be of great help if the changes are incorporated in IOS version too.
Kindly help in integrating the changes done in android version to IOS version.
Thanks in advance
Regards

**Comment by varunmashru** [comment]
Second that. I think this should be possible. Me and @prakashdevadas69 here can help you with testing.

**Comment by JohanDegraeve** [comment]
could you point me to the code in the xdripplus repository that has the changes for libre 3 support?
and/or documentation available?

**Comment by varunmashru** [comment]
@JohanDegraeve Here's the pull request for Libre Pro/H support: https://github.com/NightscoutFoundation/xDrip/pull/2075

**Comment by JohanDegraeve** [comment]
If I do initial coding (creating a new transmitter type, ..)
do you think you could do the necessary changes?

**Comment by varunmashru** [comment]
Unfortunately, I do not have the required skills to do that. I'm a Product Designer and mostly into front-end. I'm learning my way around Swift. Is there something small I can do?

Btw, adding support for Libre Pro would help thousands of users just from India immediately. Tomato has been sucking a lot lately for us.

**Comment by JohanDegraeve** [comment]
Ok i'll check first to see if it's a complex change. I'll keep you informed

**Comment by varunmashru** [comment]
Thank you very much. I'll be available for any kind of testing and support.

**Comment by prakashdevadas69** [comment]
Thank you Johan for taking up to provide libre pro support.
The changes in xDrip plus was done by @tzachi_dar & @keencave. I will request them to share additional documentation that would help you incorporate the changes quickly.
You can either give us the TestFlight link or the modified code for us test and give feedback.

**Comment by prakashdevadas69** [comment]
@JohanDegraeve 
As per the update received on Facebook (couple of months back), xDrip4iOS works with Libre Pro on eDroplet specific firmware version 4.0.

I was checking the same and found that crc Check is not done for Libre Pro( Code: LibreSensorType.swift - Line no: 83)
Probably, if you add CRC check inline with xdrip+, we are through...!!
Kindly review and let us know for further testing..

Thanks in advance
Prakash

**Comment by JohanDegraeve** [comment]
> I was checking the same and found that crc Check is not done for Libre Pro( Code: LibreSensorType.swift - Line no: 83) Probably, if you add CRC check inline with xdrip+, we are through...!! Kindly review and let us know for further testing..
> 
That will not change anything on the contrary.

**Comment by prakashdevadas69** [comment]
Yes..I did notice after going through further …but require more changes..sorry..

**Comment by paulplant** [comment]
Closed after merging Libre Pro H support into master branch in version 4.10.0.

Thanks for your work on this @prakashdevadas69 !
