### ISSUE TITLE
Alarms with multiple criteria 

### ISSUE THREAD

**Issue by Atharon** [JohanDegraeve/xdripswift#349]
Feature request:
 Is it possible to have an alarm that goes when 2 criteria meets? Like, when BG is rising above 10 and going up for more than 0,6mmol? Due to my fast acting insulin, I don’t mind the fast rising under a certain threshold before my insulin kicks in, but if it’s still fast rising after for example 10 or 11 BG, I need to act. Same for going low.

**Comment by Atharon** [comment]
Issue #186 seems the same, but opposite. Maybe they can be merged? @paulplant

**Comment by paulplant** [comment]
Agreed!

So let's close this and comment it on @LiroyvH 's issue
