### ISSUE TITLE
Misleading comment about bubbleHeaderLength

### ISSUE THREAD

**Issue by gui-dos** [JohanDegraeve/xdripswift#35]
The following comment is misleading:
```
    // length of header added by Bubble in front of data dat is received from Libre sensor
    private let bubbleHeaderLength = 8
```
(https://github.com/JohanDegraeve/xdripswift/blob/f2d7bc5303094ba238d7dc8c9a0daeb70f682421/xdrip/Transmitter/CGMBluetoothTransmitter/Libre/Bubble/CGMBubbleTransmitter.swift#L37-L38)

Bubble adds a footer of 8 bytes at the end of the FRAM when sending the data packet.

xdripswift itself is accumulating the patchUid and the first 344 FRAM bytes from the data packet reaching the same length of 352 bytes.

**Comment by JohanDegraeve** [comment]
Hi,

ok. Is it possible to make a pull request ?
This code is actually from Bubble Dev team. I reshuffled some code but this comment is original.

thanks,

Johan

**Comment by JohanDegraeve** [comment]
I think this comment is correct.  The header is in front, which is the sensor serial number https://github.com/JohanDegraeve/xdripswift/blob/master/xdrip/Transmitter/CGMBluetoothTransmitter/Libre/Bubble/CGMBubbleTransmitter.swift#L170

the data is after the header : https://github.com/JohanDegraeve/xdripswift/blob/master/xdrip/Transmitter/CGMBluetoothTransmitter/Libre/Bubble/CGMBubbleTransmitter.swift#L193
ibreData: (rxBuffer.subdata(in: bubbleHeaderLength..<(344 + bubbleHeaderLength)))

**Comment by gui-dos** [comment]
The patchUID, the serial number is computed from, comes  with the packet whose response type is 0xC0.
The patchInfo comes with the new packet whose response type is  0xC1.
Then comes the data packet, whose response type is 0x82 and whose length is 352 byte: 344 FRAM bytes plus 8 null footer bytes.

In the xDrip sources the constant 8 is called indeed BUBBLE_FOOTER:
https://github.com/NightscoutFoundation/xDrip/blob/b7bc355cea2128f72a4e09c82ce1d937e14c81e0/app/src/main/java/com/eveningoutpost/dexdrip/Models/Bubble.java#L52s

I tested all this thoroughly with https://gist.github.com/gui-dos/83fbd9b6f3a7dfe17b2dd77a59c8ddde

**Comment by JohanDegraeve** [comment]
The packet which starts with 0xC0 is added to the rxBuffer, at that moment the rxBuffer is still empty

https://github.com/JohanDegraeve/xdripswift/blob/master/xdrip/Transmitter/CGMBluetoothTransmitter/Libre/Bubble/CGMBubbleTransmitter.swift#L160

Then come several packets 0x82, these are being appended to the rxBuffer, which means after the first packet
https://github.com/JohanDegraeve/xdripswift/blob/master/xdrip/Transmitter/CGMBluetoothTransmitter/Libre/Bubble/CGMBubbleTransmitter.swift#L164

Once all packets are received, the full data is processed, starting by reading the serialnumber
https://github.com/JohanDegraeve/xdripswift/blob/master/xdrip/Transmitter/CGMBluetoothTransmitter/Libre/Bubble/CGMBubbleTransmitter.swift#L170 which is the first 8 bytes.

So i think the name and comment are correct

**Comment by gui-dos** [comment]
The newer firmwares are sending the 0xC0 patchUid packet, the 0xC1 patchInfo packet and the 0x82 data packets, in this sequence.

If you are going to accumulate also the patchInfo in the unified rxBuffer, you will have to change  the bubbleHeaderLength constant. But are the patchUid and the PatchInfo really a "header"?

**Comment by JohanDegraeve** [comment]
I haven't started yet with support of new firmware versions.

It's just the way it's coded. I could have processed packet 0xC0 immediately when receiving (ie decoding the sensor serial number). In that case the header length definition wouldn't be needed at all.

After all it's not a header indeed, as it's a seperate packet.
But I don't believe right now this comment or property name needs to be changed.

**Comment by gui-dos** [comment]
Unfortunately https://github.com/jizhongwen/xdripswift hasn't been updated since August even if on TestFlight there have been published more updated betas. Curious to have a look to their implementation :).
