### ISSUE TITLE
iPhone installation

### ISSUE THREAD

**Issue by molly200** [JohanDegraeve/xdripswift#355]
Hello,

I was wondering,, what other options does one have to install the xdrip4ios in a more user friendly way.

I'm  a 60 years year old male with diabetes and due to privacy issues I am looking for alternatives to monitor diabetes via the iPhone.  I am using Dexcom G6 as the daily monitor and can't use the Dexcom app for a number of personal reasons. Despite this fact, the company was kind enough to send me a stand alone reader. 

Searching for another  alternative, I stumbled upon this app. However, it appears that the app can only be installed via the Apple Testflight,  with the help of an invitation code from xDrip4iOS Public Group via Facebook. 

Trying to open an Facebook account, presents me with the same privacy challenges. They want me to upload my picture provide personal information etc., in order to get an account. 

Are there any other ways to get an invitation, or will this app be available on Apple store any time soon? Are there any other forums where I can subscribe for a Testflight code?

I am not a computer savvy and it took me some time to even get here!

Does anyone have any helpful suggestions?

Thank you for your time and help!

**Comment by JohanDegraeve** [comment]
search for "shuggah" on the appstore.
