### ISSUE TITLE
A test “companion” mode for Libre 2 / LibreLink

### ISSUE THREAD

**Issue by gui-dos** [JohanDegraeve/xdripswift#362]
If you just activate the notifications on the Libre 2 read characteristic without sending the unlock payload and then launch LibreLink, you can receive the data regularly while keeping both apps running side-by-side, even after closing LibreLink.

https://github.com/JohanDegraeve/xdripswift/blob/f487db5712eb37838de07d65eaaff119ea98cda3/xdrip/BluetoothTransmitter/CGM/Libre/Libre2/CGMLibre2Transmitter.swift#L242

This is technically possible on iOS with any app since in CoreBluetooth the connections are reference-counted and a device has no clue that the same characteristics’ values will be notified to all the multiple apps that subscribed to them.

It could be a way to test the app without activating BLE on your own since LibreLink can keep on reconnecting successfully to the sensor and turning off the red exclamation mark regarding the alarms unavailability in a couple of minutes.

I implemented it very easily in the “Test” mode of https://github.com/gui-dos/DiaBLE so I think that porting it will be quite doaBLE :-)

**Comment by JohanDegraeve** [comment]
test mode means LibreLink and DiaBLE run in parallel?
The patchInfo is needed to decrypt the data, that patchInfo is received via NFC (and changes with every NFC scan). 
So it's the app that did the NFC scan that can do something with the data. So what's the purpose of the 'sniffing' ?

**Comment by gui-dos** [comment]
To decrypt the BLE streaming of data only the sensor UID is needed: https://github.com/JohanDegraeve/xdripswift/blob/f487db5712eb37838de07d65eaaff119ea98cda3/xdrip/BluetoothTransmitter/CGM/Libre/Utilities/Libre2BLE.swift#L58.

A preliminary NFC scan obviously is useful to get also the sensor `patchInfo`, the factory calibration parameters and the latest 8-hour historic data but it is not required since the sensor UID is also transmitted in the last 6 bytes of the advertised manufacturer data (you have to append `[0x07, 0xe0]` as Glucose Direct is also doing in https://github.com/creepymonster/GlucoseDirect/blob/cdb8ee8bbabde9887dd9fa06eec3b86c78d65021/App/Modules/SensorConnector/Libre2Connection/Libre2Connection.swift#L84-L86.

In the newer secured Libre 2 US/CA the sensor is not transmitting its UID anymore, in fact…

Many Facebook evangelists are suggesting that you have to hide the reader in a oven in order not to loose your connections or you have to wait for the next sensor to get again LibreLink’s alarm but these are no sense: uninstalling and reinstalling LibreLink always restores its alarms since the app simply establish a new unlock code and resets the unlock count.

Sniffing the incoming BLE data lets you test different apps without knowing their unlock codes and count and braking their pairings.

It is the same technique I am using to sniff the Libre 3 incoming BLE traffic.

I had to rewrite my naive Log class that used just a single @Published String: with a LazyVStack and multiple Text lines luckily I can analyse now flawlessly the much larger amounts of transmitted data without freezing B-)

**Comment by JohanDegraeve** [comment]
Ok. Some users might be interested to have a follow mode (similar to what is available for Dexcom users : 'Follow Dexcom App', in which case the official Dexcom app is installed and xDrip4iOS just receives the readings.

But it looks a bit more complex for Libre, i mean for the user. Because an initial scan looks needed (not only useful) to get the  Libre Derived algorithm parameters : https://github.com/JohanDegraeve/xdripswift/blob/f487db5712eb37838de07d65eaaff119ea98cda3/xdrip/BluetoothTransmitter/CGM/Libre/Libre2/CGMLibre2Transmitter.swift#L383

right?

Does that mean you're able to read Libre 3 readings using the sniffing method?

**Comment by gui-dos** [comment]
Yep: however you can continue to scan via NFC both using LibreLink and your app without any problem. You can verify that the sensor sends via BLE a 0 value almost after every NFC scan and you have to interpret the temperature field as an error code which often is `0x20 (32)` that they are defining as “`RF`” because of the power consumption peak by the antenna which interferes.

This is a quick movie which shows how I am launching Libre Link after 1.5 minutes the sensor has disconnected: initially LibreLink displays a red exclamation mark but you can see that I can receive the data at the 120th second, upload them to Nightscout and, after switching back to LibreLink, the exclamation point disappears since the alarms keep on being played regularly.

https://user-images.githubusercontent.com/7220550/173927172-b63f2e08-2462-4e55-9317-7dd4a961bcdd.mov

**Comment by gui-dos** [comment]
Yep: you can verify that the Libre 3 sends every minute 35 bytes, less than the 46 bytes sent by the Libre 2, as two packets of 15 and 20 bytes.

If you reconnect after some hours you can sniff a longer stream of “clinical data” (I noticed until a maximum of 120 packets) since the sensor clearly saves the historic data every 5 and not 15 minutes now and keeps all 14-day historic data like the Indian Pro.

There is a “patch control” characteristic that lets you request the past data. According to Juggluco’s author
```
 010101 9B48 0000
```
for example lets you request the clinical data from the lifeCount `0x9B48` (18587 minutes).
Each patch control command is made of 7 bytes: there is one to shut down the sensor via BLE and others to restore the factory data and an error log.

On rooted Android you can analyze all the sensor events in detail with Free Three but I like to explore the things differently by using my “own dog food”…

Of course I am sniffing just the raw data: our Vendor is using now the advanced anti-debugging and anti-tempering industry solutions by whiteCryiption / Zimperium and decrypting the data will be almost impossible.

But I am sure they left some backdoor open even this time: you can notice for example that they are still defining the traditional “BLE Login” characteristic and even a debugging one…
