### ISSUE TITLE
Iphone 12 pro - nfc scan wont get a valid reading - libre 2 direct

### ISSUE THREAD

**Issue by KevinDenys** [JohanDegraeve/xdripswift#373]
Since switching to a iPhone 12 Pro I just can't seem to connect my libre 2 sensor to xdrip, I always get a exlamation mark, I get the message the sensor is connected but the status stays on "scanning", all info is there except the "Sensor started" where the date should be. 

I checked the serial numbers from previous working ones those where 3MH00xxxxxx but the one I have issues with now is 3MH06xxxxxx, did they change something? Am I doing something wrong? It have been trying to connect it for over a hour now.

**Comment by nils-evert** [comment]
For me it has been always like this on an iPhone 13 Pro. Simply scan several times. Or use xDrip algorithm shortly to scan.

**Comment by LiroyvH** [comment]
Yep, essentially just: keep trying until it says succes.
