### ISSUE TITLE
Allow delete bad readings

### ISSUE THREAD

**Issue by miguelpruivo** [JohanDegraeve/xdripswift#381]
One should be able to delete bad readings due to new sensor calibration. Now I can’t see the daily graph properly due to it. Even the last 24h shows as flat line because of it. 

![41EA9BC6-E5CA-4D23-AE62-19F9DE3A4A8A](https://user-images.githubusercontent.com/27860743/188716493-d02f6420-673e-410e-aebd-d20a59c836ce.jpeg)

**Comment by paulplant** [comment]
Done in #450
