### ISSUE TITLE
Libre 3 librelinkup follower

### ISSUE THREAD

**Issue by Samhagberth** [JohanDegraeve/xdripswift#399]
It would be great to get the bg values  from librelinkup into xdrip4ios and also put an optional weighted average filter to make the curve more loop friendly

**Comment by wiegerthefarmer** [comment]
Agreed! This would be amazing. And without the night guard requirement.

**Comment by gui-dos** [comment]
According to positive feedback from FB users (even US) @creepymonster’s implementation is quite effective: https://github.com/creepymonster/GlucoseDirect/blob/main/App/Modules/SensorConnector/LibreConnection/LibreLinkUpConnection.swift

My own implementation goes further by scraping also the logbook data (https://github.com/gui-dos/DiaBLE/blob/main/DiaBLE/LibreLink.swift) but I am not on TestFlight and happy to share the code and more development tips anyway :-)

**Comment by cooldad83** [comment]
This is great. Can't wait to try it out!

Aaron Visser | Senior Systems Analyst | School of Computing | Queen's University | [A button with "Hear my name" text for name playback in email signature] <https://www.name-coach.com/aaron-visser>
________________________________

**Comment by amathar** [comment]
Yes, getting librelinkup data into xdrip4ios would be great :-)

**Comment by julesjwoods** [comment]
Yeah this could be very useful for Libre 2 users as well to allow xDrip features while using Libre Link official rtCGM Bluetooth.

**Comment by 3djc** [comment]
Should this be closed as I think it has been done in #473 ?

**Comment by JohanDegraeve** [comment]
> Should this be closed as I think it has been done in #473 ?

yes can be closed
