### ISSUE TITLE
nightscout HTTPS custom port is not consistently added to the URL using for REST API

### ISSUE THREAD

**Issue by gjbadros** [JohanDegraeve/xdripswift#400]
The requests coming from xdrip4ios for (at least) api/v1/entries/sgv.json and /api/v1/experiments/test are lacking the port number in the URL requested. I suggest a quick static analysis to investigate where the ":" and port number are missing.  This causes it to break for a NS backend that runs on a non-standard (not 443) port.  

![xdripswift-missing-ns-port](https://user-images.githubusercontent.com/1500109/204058589-4633d37d-5837-44ac-8f52-5ce66338d139.png)

**Comment by paulplant** [comment]
Yes - I noticed this last month. I've already fixed it on a local branch but I've got side-tracking into the Libre 2 NFC re-write.

I'll hopefully get around to pushing a fix for this in the next weeks.

**Comment by paulplant** [comment]
Fixed

**Comment by nibbl84** [comment]
kind
we can't connect xDrip4iOS to nightscout writes on the phone when we entered the link and API that - sll error occurred (although it was put on the server and the site is accessible via it).
Can you tell me what I can do?
