### ISSUE TITLE
xdrip app extremely slow/lagging

### ISSUE THREAD

**Issue by DarkObscurity** [JohanDegraeve/xdripswift#402]
Hi!

From time to time I've had an issue with the app that it becomes extremely slow/starts lagging interface wise.

Every press is delayed and the animations are stuttering. I couldn't find anything on other people having similar issues, so I assumed there might have been something wrong with the app on my phone, however, 2 days ago I installed xdrip on my new phone, since it could not be migrated over, it has remembered all the settings from my old phone, but the interface is extremely slow again...

After killing the app and opening it again it works fine and fast for a few seconds, and then it starts to stutter again..

I also noticed that since it started doing this it had a lot of missed readings, I don't know if that's related to the app being extremely slow/lagging.

Does anyone maybe have an idea what might be causing these issues, or how to resolve them?

**Comment by LiroyvH** [comment]
Is this TestFlight or built from source? And please provide xDrip4iOS version, iOS version and exact iPhone model.

**Comment by DarkObscurity** [comment]
> Is this TestFlight or built from source? And please provide xDrip4iOS version, iOS version and exact iPhone model.

My bad!

It's build from source;
Version: 4.10.6
Build: 4181
IOS Version: 16.1.2
iPhone model: iPhone 14 Pro Max

**Comment by paulplant** [comment]
Very strange. When using iCloud to transfer the app data to a new iPhone, you technically transfer everything (coredata including all BG values, settings, treatments etc) except the app container itself.

I'm guessing there is something wrong with your coredata but not sure what it could be.

Could you maybe delete the app completely from your old phone, rebuild to it and see what happens?

**Comment by DarkObscurity** [comment]
> Very strange. When using iCloud to transfer the app data to a new iPhone, you technically transfer everything (coredata including all BG values, settings, treatments etc) except the app container itself.
> 
> I'm guessing there is something wrong with your coredata but not sure what it could be.
> 
> Could you maybe delete the app completely from your old phone, rebuild to it and see what happens?

From my old phone? Not my new phone?

**Comment by paulplant** [comment]
From either really... but maybe, in order to not touch your new/main phone, it's better to completely remove the app on your old phone, rebuild it again and use the old phone to connect for a day and see what happens. This will mean it starts with fresh (i.e. empty) coredata.

**Comment by DarkObscurity** [comment]
> From either really... but maybe, in order to not touch your new/main phone, it's better to completely remove the app on your old phone, rebuild it again and use the old phone to connect for a day and see what happens. This will mean it starts with fresh (i.e. empty) coredata.

I was planning on not using my old phone anymore and wipe it entirely.. So I'll try removing it from both phones and install the app directly on my new phone. I'll update when I've done this!

**Comment by DarkObscurity** [comment]
I had to rebuild it a few times, but now after testing for a few days everything seems to be working fine again! 
Thanks a lot!
