### ISSUE TITLE
New Suggestion - bluetooth battery level

### ISSUE THREAD

**Issue by clvsjr9** [JohanDegraeve/xdripswift#42]
Any way to view bluetooth battery level?

Maybe some status screen as with the transmitter:

![BattStatus](https://user-images.githubusercontent.com/12844781/70854404-a1b05300-1e91-11ea-9cb4-6253de975538.jpg)

**Comment by JohanDegraeve** [comment]
what do you mean with "bluetooth battery level" ?

I only know the transmitter battery level

**Comment by clvsjr9** [comment]
M5Stack battery level.

**Comment by JohanDegraeve** [comment]
ah ok I see.
Apparently Martin Lukasek has a getBatterLevel function in his project.
That would mean yes it's possible.

I'll try to do it for the next release. It will be in the m5stack overview

**Comment by clvsjr9** [comment]
If possible also an option to turn off M5Stack directly from the xdripswift app to save battery power.

Martin Lukasek did using buttonC

![PowerOff](https://user-images.githubusercontent.com/12844781/70854717-e8a04780-1e95-11ea-9e77-6e60a300e03a.jpg)

**Comment by JohanDegraeve** [comment]
Yes I'll do that at the same time

**Comment by JohanDegraeve** [comment]
Fixed in commit edc27ce6cf1ad2f6694ebeddfa7aeeb514922092
will be available in the next release
