### ISSUE TITLE
SAGE not updated in NS

### ISSUE THREAD

**Issue by LiroyvH** [JohanDegraeve/xdripswift#423]
The sensor start time (SAGE) is no longer uploaded to Nightscout since the latest update. Had already mentioned it internally and is now also confirmed by @bjornoleh.

**Comment by bjornoleh** [comment]
Thanks for confirming!

**Comment by bjornoleh** [comment]
This was fixed by https://github.com/JohanDegraeve/xdripswift/pull/434, and the issue can be closed now.
