### ISSUE TITLE
Relationship between current level and rise/fall rate?

### ISSUE THREAD

**Issue by LJWatson** [JohanDegraeve/xdripswift#431]
What is the relationship between the current glucose reading and the previous reading, and the amount by which XDRIP reports it has risen/fallen? 

I've noticed that the numbers don't seem to add up. For example, three consecutive readings today are:

-0.4mmol/l
7.3

-0.5mmol/l
7.1

-0.5mmol/l
7.0

If the level drops by 1.0 (twice 0.5)  between the first and third readings, I'd expect the level to drop from 7.3 to 7.2, not 7.3 to 7.0.

Perhaps I'm misunderstanding what the rise/fall numbers actually represent, but mentioning it here in case there is something up with either the algorithm or the display.

**Comment by paulplant** [comment]
Try reading through the following issue and see if this helps to explain. If not, feel free to comment again:

https://github.com/JohanDegraeve/xdripswift/issues/422

**Comment by paulplant** [comment]
@LJWatson - please confirm that the above link answers your questions so that we can close this as an issue. Thanks!

**Comment by LJWatson** [comment]
Thanks @paulplant. It did make sense, so I've posted some thoughts over on #422 and this issue can be closed.
