### ISSUE TITLE
Nightscout upload "Sensor Started" inconsistent with Nightscout's sensorage.js plugin "Sensor Start"

### ISSUE THREAD

**Issue by loopy321** [JohanDegraeve/xdripswift#433]
Can this be changed back to "Sensor Start"?

https://github.com/JohanDegraeve/xdripswift/commit/58185737f8cb99941a49915b9d6369e1ef12de1d#r106810809

Changing from "Start" to "Started" causes [Nightscout's sensorage.js plugin](https://github.com/nightscout/cgm-remote-monitor/blob/a09e586b95065d502390475bb4ec415f95c7eff5/lib/plugins/sensorage.js#L53) not to work as it did previously.

**Comment by loopy321** [comment]
[Pull request.](https://github.com/JohanDegraeve/xdripswift/pull/434)

**Comment by bjornoleh** [comment]
Thanks! The PR was merged, and has been confirmed to work. This issue can be closed now.
