### ISSUE TITLE
Big difference in glucose values between xDrip and Libre app

### ISSUE THREAD

**Issue by DarkObscurity** [JohanDegraeve/xdripswift#437]
Hello!

I recently started to notice that xDrip has completely different glucose values compared to the actual Libre app and a manual test.
Now I know that the measurements from a Libre 2 sensor will be off and delayed in comparison to a manual check, but the there is also a (in my opinion) huge difference between both apps, I already tried to replace the sensor, but the next one has exactly the same difference, here is a list of values; (x = xDrip and L = Libre app)
- L: 7.2 X: 5.7
- L: 6.9 X: 5.3
- L: 5.4 X: 4.1

And this goes on... I can't really rely on xDrip this way.. the previous sensor I ended was even worse, xDrip showed 2.8 while my finger prick showed 6 and the Libre app showed 5.5.

I've never had this issue before, so I'm curious if there is anything I can try to get it closer to the values of the Libre app again?

I'm using xDrip on an iPhone 14 Pro max
IOS: 16.4.1
xDrip version: 4.10.6
xDrip Build: 4181

**Comment by DarkObscurity** [comment]
> If you don't like the results of the Libre Algorithm, then you could consider manual calibrations instead - either single or in multi-point mode (also known as non-fixed slope). Refer to the user manual for more information and best practices.

Just out of curiosity, how could there be such a huge difference between the Libre app and xDrip using the Libre algorithm?

**Comment by LiroyvH** [comment]
@DarkObscurity: The LibreLink-app runs a different version of the algorithm and the smoothing may be different. Either usually works reasonably similar for most people, but with some people and/or some sensors the differences may be larger; in which case using one of the manual calibration algorithms is a better option.
