### ISSUE TITLE
Suggestions to new icons

### ISSUE THREAD

**Issue by clvsjr9** [JohanDegraeve/xdripswift#44]
New suggestion: https://cocoapods.org/pods/Swift-Icons

**Comment by clvsjr9** [comment]
For this view:

![icons](https://user-images.githubusercontent.com/12844781/71589923-0e1b8b00-2afd-11ea-8b30-410389a4a5d7.jpg)

And others parts of project too ....

**Comment by gui-dos** [comment]
I always wondered why the system Bluetooth icon isn't made available by Apple. The one in

```/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/SpringBoardHome.framework/Assets.car```

seems the correct one (you can preview it with [AssetCatalogTinkerer](https://github.com/insidegui/AssetCatalogTinkerer)).

**Comment by JohanDegraeve** [comment]
icons changed in 4.0.0
