### ISSUE TITLE
Failing to pair with sensor and possibly cause the sensor become dead

### ISSUE THREAD

**Issue by Mitya1983** [JohanDegraeve/xdripswift#442]
Today had an issue with connecting libre2 sensor via Bluetooth. NFC scan is successful but Bluetooth is not. After such operation native app says that sensor is invalid and asks to replace sensors. Thought that this may be the sensor issue and replaced the sensor. With new one issue is the same.

**Comment by paulplant** [comment]
This is not an app issue, but a general technical support request. 👍

We offer tech support in the official Facebook group here:

https://www.facebook.com/groups/853994615056838
