### ISSUE TITLE
input field for minutes (alarms)

### ISSUE THREAD

**Issue by zshh** [JohanDegraeve/xdripswift#45]
To change the time for example (missed signal 15 minutes), the field itself says "minutes", but if you enter 15, it will pick some high decimal number instead. 

so 20 minutes or whatever it was default you need to enter 1.7 in the field. A bit confusing and also, keyboard input (OSD) to enter this does not have "." (dot) in it.

**Comment by JohanDegraeve** [comment]
if you say 15 it will pick a high decimal number ? I don't understand. Can you add a video ?

. (comma) is only available for bg reading alerts, if you have mmol as unit

**Comment by zshh** [comment]
[https://youtu.be/uJh38hVmkfc](url)

Here is the video. You can see that initially says 18 minutes. When i click to change it, it says 1.0.
If i change the value to 15 (as in 15 minutes) and click OK, it changes to 270 minutes.

Same if I then change to 1, it changes to 18 minutes.
So 15 minutes would maybe be 0.8 or something by that logic, but there is no "." on the OSD keyboard either. Bit of catch 22.

**Comment by JohanDegraeve** [comment]
oh that's a good one. 
If you would set the unit to mgdl then it will work correctly. Temporary workaround is to set unit to mgdl, set the missed reading alert, then go back to mmol

i'll fix this in the next release

**Comment by zshh** [comment]
Yeah mgdl workaround fixed the issue, thanks :)
