### ISSUE TITLE
Implement a “Contact Trick” to update BG as watchOS complication

### ISSUE THREAD

**Issue by callms** [JohanDegraeve/xdripswift#481]
As suggested by @paulplant in #479, we might consider porting the [Contact Trick](https://github.com/open-gluck#the-contact-trick) used by OpenGlück in xDrip4iOS.

This trick allows to update the photo of a contact, so that its profile picture matches the current BG. This, in turn, can be used on Apple Watch to provide near-realtime update of the current BG, without usual WidgetKit restrictions.

Image from OG showing how it renders on the watch:

![image](https://github.com/JohanDegraeve/xdripswift/assets/66381046/9f45bc66-63e2-48a9-842f-3b7c4edb2dde)

**Comment by paulplant** [comment]
I'll close this as an issue as we are now tracking it directly in a PR -> #505
