### ISSUE TITLE
Immediate Crash after setting to LibreLinkUp follower

### ISSUE THREAD

**Issue by OliNix** [JohanDegraeve/xdripswift#484]
xDrip4iO5 version: 5.0.0
iOS version: 17.1.2
Hardware: iPhone 14 Pro, Libre 2
Other: Loop user

After setting app to follower mode and inputting my LibreLinkUp credentials, the app crashed. Now when I try to relaunch I get an immediate crash and quit.

**Comment by OliNix** [comment]
I have managed to change back to Master mode before the app crashed and quit.

This reinstated the stability and eliminated the crashing

**Comment by paulplant** [comment]
Without any log files, there's no way to troubleshoot this. We put lots of error handling into the LibreLinkUp connection and I never once had a crash during the months of development and testing.

Are you able to try and reproduce this again? If so, then immediately send an Issue Report (with a brief description) from within the app.

**Comment by OliNix** [comment]
I have been unable to recreate since its initial occurrence and updating to 5.0.1.

I will try to downgrade and recreate in the coming days

**Comment by OliNix** [comment]
Unable to recreate.

Please close issue, I will re raise with logs if reoccurs
