### ISSUE TITLE
Alarms don't work

### ISSUE THREAD

**Issue by artoritorian77** [JohanDegraeve/xdripswift#485]
Hello!

I installed the new version 5.0.1 and the alarms stopped working.
iphone 13 mini ios 17.2.1
iphone SE 2022 ios 17.2.1

I updated because I noticed a problem after update ios 17.2.1 on the master on version 4.12.0 - the alarm about missed readings stopped coming. Now (5.0.1) all alarms stopped :-(

Are you aware of this problem? When to expect fixes?

PS Thank you for what you do!

**Comment by paulplant** [comment]
should be fixed in #486 (ignore that it says "Nightscout follower alarms")
