### ISSUE TITLE
Missing Readings Until xDrip is Closed and Re-Opened

### ISSUE THREAD

**Issue by kaabiio** [JohanDegraeve/xdripswift#487]
Are there any known fixes for readings cutting out? Will get notification for missed readings, I’ll then close and re-open app and then readings will appear. If I don’t close and re-open the app then unfortunately it won’t bring readings back. The readings save to the transmitter but it can’t seem to wake the app back up. Happens about 10-20x per day and sometimes when sleeping. 

Deleting app and starting from scratch seemed to help it for a month but the issue is back in full force for me now - latest xDrip version - thanks!!!
![IMG_9771](https://github.com/JohanDegraeve/xdripswift/assets/32051388/c44f6bff-dd4a-46d0-873b-a489f17d286d)
![IMG_9772](https://github.com/JohanDegraeve/xdripswift/assets/32051388/5444c389-7b2e-47c7-a300-d4e2f21cc488)

**Comment by jonisaksson** [comment]
I have been wondering if 'Low Power Mode' on the iphone could impact the connection. I can see that you only have 13% battery power... did you enable Low Power Mode by any chance?

**Comment by kaabiio** [comment]
Low power mode wasn’t on when these screenshots were taken, it would make the battery icon yellow - also happening here and there this morning with my battery at 88%. I do use low power mode from time to time but it doesn’t seem like this issue discriminates based on if it’s on or not

**Comment by paulplant** [comment]
Closing as this is already reported on the Facebook group and seems user-specific, not a general issue.
