### ISSUE TITLE
miaomiao sensor status

### ISSUE THREAD

**Issue by johnamon** [JohanDegraeve/xdripswift#5]
When paired with a miaomiao transmitter, Sensor Start appears as 'not started' - despite session already started via the offical app.  No option to start a session appears available.

**Comment by JohanDegraeve** [comment]
How did you solve this ?
I found a bug actually related to MiaoMiao sensor start, will be solved next release, should be available within 24 hours.

**Comment by johnamon** [comment]
Hi Johan,

I didn't solve it, after raising the issue I noticed the change description
that you'd entered for the recent fix - so I closed the issue out to
prevent clutter.

I really appreciate the work you're putting into xDrip & that you've made
it available to test - thanks!

Thanks!

John
