### ISSUE TITLE
watchkit storyboards in watchos 7.0

### ISSUE THREAD

**Issue by HDBAPro** [JohanDegraeve/xdripswift#506]
Hi
I'm having an issue during xdripswift installation "watchkit storyboards are deprecated in watchos 7.0"

Domain: IXUserPresentableErrorDomain
Code: 1
Recovery Suggestion: Extensionless WatchKit app com.XXXXXXXXX.xdripswift.watchkitapp has a WatchKit extension.
User Info: {
    DVTErrorCreationDateKey = "2024-03-15 10:51:31 +0000";
    IDERunOperationFailingWorker = IDEInstallCoreDeviceWorker;
}

![1](https://github.com/JohanDegraeve/xdripswift/assets/44998140/4aca18e1-7785-402f-b64c-58e566901b14)

**Comment by paulplant** [comment]
This is just an Xcode compiler warning. It isn't an error and it won't cause anything to go wrong. You can ignore it.

The next release has a completely new Watch App written entirely in SwiftUI so this warning will soon disappear anyway.

Feel free to comment, but I'll close this Issue as it isn't actually an issue at all 👍

**Comment by HDBAPro** [comment]
But I still have some issues that won't let xdripswift to install. I tried both master and develop branches. Both didn't compile and install.
```
xdrip has conflicting provisioning settings.
xdrip is automatically signed, but code signing identity (XDRIP_CODE_SIGN_IDENTITY_RELEASE) has been manually specified. Set the code signing identity value to "Apple Development" in the build settings editor, or switch to manual signing in the Signing & Capabilities editor.
```

**Comment by paulplant** [comment]
This issue is fixed outside and will be merged to develop in the next days
