### ISSUE TITLE
Change the name of this app to something less confusing

### ISSUE THREAD

**Issue by dideldum** [JohanDegraeve/xdripswift#51]
As this app is not related to the original xDrip and also not related to xDrip+, which has replaced the original xDrip, it is a very bad idea to call this completely different iOS app also xDrip. Even though it takes ideas from the Android xDrip+ app, it is a completely different development, isn't it?
It was a bad idea to call the previous app iosXDRIPreader, which also was abbreviated as xdrip by many people. And it is a very bad idea to call this app again xdrip.
Choose a different name to make clear, that this is a different app.

**Comment by JohanDegraeve** [comment]
app is renamed in 4.0.0
