### ISSUE TITLE
Suggestion: add App Group capability

### ISSUE THREAD

**Issue by clvsjr9** [JohanDegraeve/xdripswift#52]
To share data and communicate between apps using the same group name.

xDripSwift <---> Loop.    integration using App Group capability

Using Mach messages on iOS: 

http://ddeville.me/2015/02/interprocess-communication-on-ios-with-mach-messages

And

Mach ports are light-weight and powerful, but poorly documented:

https://nshipster.com/inter-process-communication/

**Comment by clvsjr9** [comment]
I invite you to know an example that I programmed that demonstrates the functionality presented here in this issue like a suggestion.

https://github.com/clvsjr9/IPC-Example

**Comment by JohanDegraeve** [comment]
Hi, 

maybe something to send also to Cal Young also ? who developed the loop-spike branch ?

I'll look again into the webservice proposal this week.

regards,

Johan

**Comment by clvsjr9** [comment]
I sent invite to dabear (Bjorn Inge Berg) - the creator of loop-spike branch and  Cal Young - the maintainer and support of loop-spike branch currently.

**Comment by clvsjr9** [comment]
To be publicly registered I received the following consideration: 

Pete Schwamb: CGMManager is a swift protocol. CGM managers should be implemented as plugins in Loop, that conform to the CGMManager protocol. So you would have a xDripSwift CGMManager plugin in loop, and it could use whatever IPC mechanism it wants to to talk to xDripSwift.

Pete Schwamb: You could create a simple coredata database that xDripSwift would write to. Both xDripSwift and the xDripSwift CGMManager plugin could share the same framework that implements the code for storing and reading to that database.

**Comment by JohanDegraeve** [comment]
Has been added in version 4.0.0
Here's an explanation given by Julian Groen https://github.com/julian-groen/xdrip-client-swift
