### ISSUE TITLE
Widget colours are hard to see in Nightstand mode

### ISSUE THREAD

**Issue by OliNix** [JohanDegraeve/xdripswift#523]
When:
- phone is on charge and rotated sideways (in nightstand mode)
- the widget is running
- Light levels are low in the room (display changes from full colour to red only)

The high sugar level colour is very hard to see. See the left hand side of the screenshot below. The dark red colour also applied to the sugar level value when it is high (not in screenshot as I only realised when I was back in range).

![image](https://github.com/JohanDegraeve/xdripswift/assets/16334811/88ab5796-2c7e-4f95-b6c8-8e3874fe5688)

Can the colour scheme please be reviewed?

**Comment by OliNix** [comment]
Added screenshot showing hard to read BG value![image](https://github.com/JohanDegraeve/xdripswift/assets/16334811/bf34acf2-a250-437a-b0e0-7972321beeee)

**Comment by paulplant** [comment]
@OliNix , can you confirm that this was fixed in 5.2.0? If so, please mark as closed 👍

**Comment by OliNix** [comment]
Issue resolved with updated colour scheme
![image](https://github.com/JohanDegraeve/xdripswift/assets/16334811/05127268-d78c-4fde-b8ff-69b1abcb27a7)
![image](https://github.com/JohanDegraeve/xdripswift/assets/16334811/4111cafd-f19c-4c57-99db-715ecd1af92c)
