### ISSUE TITLE
Heartbeat Missing for Trio

### ISSUE THREAD

**Issue by MikePlante1** [JohanDegraeve/xdripswift#555]
All my tests were in-vivo, I kept my G6 connected to the official Dexcom app and checked "Read from Dexcom app" in xDrip4iOS' Bluetooth menu. I then used xDrip4iOS as the cgm source in Trio.

+ [Trio-dev](https://github.com/nightscout/Trio/commit/bd56601448bf44d11579988e7a9f5e5fa77481db) + xDrip4iOS v5.2.3
(using LoopGroup)
:white_check_mark: Readings received in Trio with phone locked
:white_check_mark: Heartbeat confirmed in Trio
+ Trio-dev + xDrip4iOS v5.3.1
(using LoopGroup / Loop selected as OS-AID in xDrip4iOS)
:white_check_mark: Readings received in Trio with phone locked
:white_check_mark: Heartbeat confirmed in Trio
+ Trio-dev w/ PR314 merged into it + xDrip4iOS v5.3.1
(using trio-app-group / Trio selected as OS-AID in xDrip4iOS)
:white_check_mark: Readings received in Trio with phone locked
:x: Heartbeat confirmed in Trio
+ Trio-dev w/ [PR314](https://github.com/nightscout/Trio/pull/314) merged into it + xDrip4iOS v5.3.1 
I went into the xDrip4iOS code and changed all instances of `group.com.${DEVELOPMENT_TEAM}.loopkit.LoopGroup` to `group.org.nightscout.${DEVELOPMENT_TEAM}.trio.trio-app-group` and vice-versa. I selected Loop/iAPS as OS-AID in xDrip4iOS, but because of my flips that means it's using trio-app-group)
:white_check_mark: Readings received in Trio with phone locked
:white_check_mark:  Heartbeat confirmed in Trio

**Comment by MikePlante1** [comment]
Not sure why I couldn’t get heartbeat to work before, but it’s working now.

**Comment by paulplant** [comment]
Hi @MikePlante1 , so you can confirm that Trio receives correctly a heartbeat using the current xDrip4iOS 5.3.1 and the current share-client without needing any other changes?

To be honest, I wasn't sure how to answer your first post as it didn't make sense to me (from a functionality point of view) that you could change the heartbeat of the share-client but changing app group settings in xDrip4iOS.

Please let me know if you can test some more (I'm travelling and very limited for free time) and if it is actually working well or if we need to look into things more.

PS. Does this mean that the Trio Dana branch can work without background audio when using xDrip4iOS as the CGM source?

**Comment by MikePlante1** [comment]
So, my initial test and issue report was not the best. I was just going off of the xDrip4iOS module in Trio and not actually testing heartbeat. For my initial 4 tests, I marked them based on this:

| ✅ Heartbeat confirmed in Trio | ❌ Heartbeat confirmed in Trio |
| -- | -- |
| ![IMG_5080](https://github.com/user-attachments/assets/21b733d5-a64d-4a2e-8c0e-99f20d5c54f8) | ![IMG_5089](https://github.com/user-attachments/assets/93ef5c09-3626-4408-879e-9ba3f40f0f25) |

But the following day, I tried the same test that failed the first time, and this time it succeeded in displaying the heartbeat/cgm in Trio.

***

To actually test the heartbeat functionality, I setup the following on my real phone (iPhone 15 ProMax + iOS 17.5.1)

Trio app being used for my management:
+ [dev](https://github.com/nightscout/Trio/commit/bd56601448bf44d11579988e7a9f5e5fa77481db) (Loop App Group)
+ CGM source: Dexcom G6
+ Pump: Medtronic 722 + OrangeLink
+ Live Activities: Off

Trio app being used for the test:
+ [dev](https://github.com/nightscout/Trio/commit/bd56601448bf44d11579988e7a9f5e5fa77481db) + [PR314](https://github.com/nightscout/Trio/pull/314) (Trio App Group)
+ CGM source: xDrip4iOS
+ Pump: Simulator Pump
+ Live Activities: On

xDrip4iOS:
+ The latest [v5.3.1](https://github.com/JohanDegraeve/xdripswift/commit/fec1005899893ddf20e36675f3aad96547e8c99c)
+ Bluetooth > CGM > Dexcom G6
+ Did not start session in xDrip4iOS, instead toggled on `Read from Dexcom App`
+ Share with OS-AID: Trio
+ Share with OS-AID every 5 mins: On

Readings populated properly in Trio from xDrip4iOS from Official Dexcom G6 app and Live Activities from both apps displayed properly. I then closed (minimized, not force closed) both apps and let them run without opening them and went to bed. 7 hours later, I opened my phone and both Live Activities were displayed properly on the lockscreen, proving that the heartbeat from Dexcom G6 was properly forwarded to the Trio app from xDrip4iOS.

Later in testing, I also noted that sometimes the xDrip4iOS module will display a heartbeat/CGM address even when no CGMs were paired to xDrip4iOS. And I also see that the CGM address displayed above is the only CGM address that's ever displayed and it never changed for me. I seem to remember it changing every 5 minutes before, but maybe I don't remember that properly.

***

This leads me to believe that the heartbeat does get transferred properly to the Trio app and keeps it awake. It also seems like maybe there's a display issue regarding CGM address in Trio. If Trio is kept open properly from xDrip4iOS with a simulator pump, I would expect it to be kept open with a heartbeat-less pump like Dana.

***

I will do another test tonight where I build xDrip4iOS and Trio-dev+PR314 to a different iPhone, use xDrip4iOS in Follower HeartBeat mode via Nightscout, and see if that keeps Trio awake in the background properly using xDrip4iOS as a cgm source and a simulator for the pump.

**Comment by paulplant** [comment]
Should be fixed with #557
