### ISSUE TITLE
Libre3 -> Heartbeat-> Trio

### ISSUE THREAD

**Issue by Rig22** [JohanDegraeve/xdripswift#558]
Would it be possible for Libre 3 users to implement a heartbeat that keeps Trio running in the background? Similar to the feature for Dexcom. The heartbeat feature for Dexcom was introduced to xdrip around here: https://github.com/JohanDegraeve/xdripswift/commit/f3dd64a67cccaed5862cd91c29458f2bc67f2750
@avouspierre

**Comment by paulplant** [comment]
Probably. We can look into it but it would need the user to be using the Libre heartbeat function in xDrip4iOS.

**Comment by Rig22** [comment]
Hi Paul. 🙂 First of all, thank you for possibly looking into it. I'm not sure if I understand you correctly? Do you need someone to test it? I'm happy to help.

**Comment by paulplant** [comment]
Nothing to test yet. I'll let you know.

**Comment by paulplant** [comment]
@Rig22 , can you confirm if this issue can be closed now? 

The last update should have re-established heartbeat for Trio users. Is it fine now? Thanks!

**Comment by Rig22** [comment]
Good morning Paul. Unfortunately I can't test it at the moment because the feature/dana branch is still at the July 11th version.

**Comment by Rig22** [comment]
Yesterday I tested the current Trio Feature/dana branch with your current xdrip dev. There was no change. As before, no heartbeat from xdrip is reaching Trio. But you can still close the issue as far as I'm concerned, as I've dealt with it. Thank you for your efforts and your time.

**Comment by paulplant** [comment]
OK, we'll close it but I'm unsure about your last message. What does it mean that you've dealt with it? You've fixed it?

The seems to be an issue with only the Dana branch I think and not related to xDrip4iOS (but without more information, it's hard to really tell).

We'll close it and feel free to open another issue if you see something that is related to xDrip4iOS. Cheers!

**Comment by Rig22** [comment]
No, i don‘t fix it. I just bought a iPhone 16 Pro Max. So much battery, that i can ran the dana continous bluetooth mode the whole day. Yes, it‘s only related to dana users, because of the missing Heartbeat .
