### ISSUE TITLE
Live Activities cause too high of a resource drain

### ISSUE THREAD

**Issue by OliNix** [JohanDegraeve/xdripswift#564]
When a Live Activity is happening, it seems to call priority over every other process running on the iPhone.

To the extent that streaming music via Bluetooth is inaudible due to breaking up. As soon as the live activity is stopped, the issues disappear.

Can we consider the update frequency and process priority of the live activity?

**Comment by paulplant** [comment]
So there are probably 20k+ users (maybe a lot more) using the live activities in the app over the last 6 months and nobody has ever noticed this before.

The issue states a resource drain... are you seeing an impact in the battery or the iPhone heating up?

There is no such thing as a process priority... where do you get the information that it has priority over other processes?

Live activities can be assigned priorities within the same app to ensure a particular live activity is visible over other ones running started by the same app, but this has nothing to do with resources.

Our live activities actually have a quite slow update cycle... other apps (such as delivery tracking apps) will likely be updated every few seconds. There's no real reason why we would lower the update frequency. I'm also unsure how this can be related to bluetooth streaming?

**Comment by OliNix** [comment]
Playing around with this more, it isn't isolated to live activities.

It is either Loop or xDrip4iO5 causing the issue, but I can't currently work out which.

It seems to destabilise the Bluetooth connectivity connection to other devices.

No, not a battery drain or device getting hot. As I said it seems to be a prioritisation issue, but if this is not possible, perhaps it is an overload of requests issue, which causes other processes to drop off (like a DDoS attack)

I will close the issue till I have more information.
