### ISSUE TITLE
Seeking Solutions for Real-Time Glucose Monitoring on iPhone and Apple Watch in South Korea

### ISSUE THREAD

**Issue by rlatmdgus99** [JohanDegraeve/xdripswift#566]
Hello,

I am a Type 1 diabetes patient living in South Korea and currently using the Libre 2 sensor with an iPhone. I am trying to display my glucose data from the LibreLink app in real-time on my iPhone or Apple Watch lock screen, but I have encountered several challenges.

Here’s a summary of the issues:

1. **Sensor Type**: The Libre 2 sensors sold in South Korea are US sensors.
   
2. **LibreLinkUp Unavailability**: LibreLinkUp is not available in South Korea. Even with a US App Store account, the South Korean LibreLink app does not support connection to LibreLinkUp.
   
3. **Gluroo App Limitation**: The Gluroo app requires LibreLinkUp to function, making it unusable for me in South Korea.
   
4. **Alternative Apps**: 
   - The Spike app is difficult to use in South Korea.
   - xDrip4iOS only supports EU sensors, so it’s not an option for me.

I have explored and researched various methods, but none have provided a solution. Could you suggest any possible ways to achieve real-time glucose monitoring on my devices?

Thank you very much for your assistance.

**Comment by paulplant** [comment]
Closing this issue
