### ISSUE TITLE
Major (1.6 mmol/L) difference LibreLink and xdrip

### ISSUE THREAD

**Issue by yochem** [JohanDegraeve/xdripswift#577]
As the documentation notes:

> There will most likely be small differences between the readings shown by the LibreLink app and readings shown by xDrip4iOS.

I have been around 3.3 for more than half an hour on xdrip, and 4.8 in librelink. It's a new sensor, and an early fingerprick gave 5.8 mmol/L. See screenshots below. 

![Xdrip](https://github.com/user-attachments/assets/cd1a4469-c0b1-4e8c-91c7-5dde66c11a95)

![Librelink](https://github.com/user-attachments/assets/249c8608-b586-49dd-b19b-8558147d9550)

Is this difference to be expexted?

**Comment by yochem** [comment]
Forget to mention that I'm currently using version 5.3.3.

Last measurements:
- prick: 6.5
- libre: 4.1
- xdrip: 2.7

**Comment by paulplant** [comment]
This can happen sometimes but the fact that the sensor is already reading very far off the real value could indicate a problem with the sensor itself.

Also, checking when rising/falling will also give bigger differences compared to the LibreLink app. Maybe try enabling Smooth Libre Values option (in Developer Settings in 5.3.3 and in Libre 2 EU screen for 5.4.0.

This isn't really an issue with the app though, more an isolated issue caused (probably) by the sensor itself.

**Comment by paulplant** [comment]
The calibration function exists in xDrip4iOS for exactly this reason.

https://xdrip4ios.readthedocs.io/en/latest/configure/calibrate/

**Comment by yochem** [comment]
Thank you. Yes I calibrated now!
