### ISSUE TITLE
Volume high for first 0.5 sec of audio alert

### ISSUE THREAD

**Issue by zshh** [JohanDegraeve/xdripswift#58]
Hi,

So I have a defined alert for missed readings. 
Not sure if it matters but i use "modern alert" sound for this.

When alert triggers (no matter how low or high the actual volume on the phone is), initial 0.5 sec of the audio is very high, after that volume goes down for the rest of audio clip according to volume phone is set to.

Any idea what might be causing this?

**Comment by JohanDegraeve** [comment]
No idea actually. The sound is added in the notification content, and iOS handles it.
That looks like an iOS thing, but I couldn't find any  similar experience on the net

**Comment by zshh** [comment]
Yeah its strange. I've stumbled upon this article
https://apple.stackexchange.com/questions/358839/iphone-xr-ringer-volume-sound-loud-for-the-first-second-then-goes-real-quiet

Whether its relevant or not, we'll see, just made the change. Will update

**Comment by zshh** [comment]
Tested it now, but it didn't help :(

Anyway, you can close this one if you want, i'll just have to live with it :)

**Comment by JohanDegraeve** [comment]
Ok :)

Op di 21 jan. 2020 om 09:10 schreef zshh <notifications@github.com>
