### ISSUE TITLE
xDrip4iO5 could not scan the stelo device

### ISSUE THREAD

**Issue by fortitude1990** [JohanDegraeve/xdripswift#588]
![20241106-114528](https://github.com/user-attachments/assets/2d357c1a-eb38-48be-aa09-08fb848da310)
Hello, I used the xDrip4iO5 app to connect to stelo and did not scan the device. But I was able to detect the device using the stelo app, does anyone know why? Could you help me solve my problem? Thank you.

Here is the log printed out by xcode:
```
xdrip(51978,0x1fc3dcc00) malloc: xzm: failed to initialize deferred reclamation buffer (46) 
Couldn't read values in CFPrefsPlistSource<0x3000c0f80> (Domain: group.com.9RWFQGHP96.loopkit.LoopGroup, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null), Contents Need Refresh: Yes): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd
CoreData: annotation: Core Data multi-threading assertions enabled.
WCSession has not been activated
-[WCSession onqueue_handleUpdateSessionState:]_block_invoke dropping as pairingIDs no longer match. pairingID (null), client pairingID: (null)
WCSession is not paired
#FactoryInstall Unable to query results, error: 5
```

**Comment by paulplant** [comment]
Please use the Facebook group if possible for any type of basic support with the app: https://www.facebook.com/groups/853994615056838

GitHub is really for development topics for the app, not for user support.

Did you leave the Dexcom Stelo app running in the background? This is needed when trying to connect also with xDrip4iOS. The Stelo will only advertise and connect every 5 minutes - not sure how long you waited?

Also you have airplane mode enabled - are you sure bluetooth is still active?

The log you have shared shows nothing related to Stelo or BLE - not sure what you want us to see with it?

**Comment by fortitude1990** [comment]
According to your prompt, I successfully connected the device, thank you very much.    @paulplant
