### ISSUE TITLE
XDrip is crashing after loosing the connection with Blucon

### ISSUE THREAD

**Issue by miki3421** [JohanDegraeve/xdripswift#62]
Hi, i send a crash report from TestFlight after a crashed. 
The root cause it's seems there was a bad connection with Blucon because the battery is low. 
Now 3%.. i need to change of course. But it will be better if the app can detect and advice instead of crashing.

**Comment by JohanDegraeve** [comment]
Battery level for blucon may not be correctly reported. Blucon interface was reverse engineered without documentation from Blucon

But i see 5 crash reports for Blucon on the same place, I'll try to fix it (without having a blucon :) )
