### ISSUE TITLE
Fast rise/drop alerts

### ISSUE THREAD

**Issue by opsb** [JohanDegraeve/xdripswift#65]
Using the Spike app I found that the most useful alerts were fast rise/drop. Is there interest in adding these to xdripswift? If so I'd like to pick it up. I'm new to swift/ios development but I've been a developer for 15 years and this seems like a good little feature to start with.

**Comment by JohanDegraeve** [comment]
Hi,

looks indeed like a good little feature to start with

if you look here https://github.com/JohanDegraeve/xdripswift/blob/master/xdrip/Managers/Alerts/AlertKind.swift
by adding two enum types (fastRise and fastDrop) then you it should only be a mattter of correcting all the compile errors

**Comment by opsb** [comment]
Nice, I’ll start there then.
