### ISSUE TITLE
Proposal: Value type for BGValues

### ISSUE THREAD

**Issue by opsb** [JohanDegraeve/xdripswift#67]
While working on https://github.com/JohanDegraeve/xdripswift/pull/66 it was unclear to me how to determine whether a bg value is in mmol or mgdl. There is the user setting but for instance in the case of default values for alerts they may have existing before the user setting was available. 

I started to sketch out an API that looks like the following

```
// add same types of values
> print(BGValue.mgdl(100) + BGValue.mgdl(100))
mgdl(200.0)

// add mmol to mgdl
> print(BGValue.mmoll(5) + BGValue.mgdl(100)) 
mmoll(10.55)

// multiple mmoll by mgdl
> print(BGValue.mmoll(5) * BGValue.mgdl(5)) 
mmoll(1.3874999999999997)

// divide mmoll by mgdl
print(BGValue.mmoll(5) / BGValue.mgdl(150)) 
> mmoll(0.6006006006006006)

// compare mmoll to mgdl
> print(BGValue.mmoll(5) < BGValue.mgdl(150)) 
true

// arbitrary expression with values converted to mmoll
> print(BGValue.map2AsMmoll(BGValue.mgdl(100), BGValue.mmoll(5)) { $0 + $1 }) 
mmoll(10.55)
```

There's an initial implementation and working demo at https://repl.it/@opsb/Bg-value-types.

The main value here is that the compiler can enforce that blood glucose values are always handled correctly. A developer never need to think about whether they're dealing with `mgdl` or `mmol`, the compiler will always ensure that they're handled correctly.

It's worth considering performance as there's obviously at least some overhead to using boxed types. It may be that in tight loops the performance overhead would be an issue but in those scenarios you could unbox and work with the raw values. 

I'd be interested to hear what you think and if you happy with the proposal I'd be happy to put together a PR swapping them in for the raw double values (seems like the compiler would do most of the work).

**Comment by JohanDegraeve** [comment]
Actual stored values are always in mgdl, that's for calculated value in a bgreading, alert levels, ... 
it's only when displaying values that you need to know if the user wants to see mgdl or mmol

For instance when asking for an alert value, if user setting is mmol, then the keyboard would allow to enter decimal. After entering a value, the value needs to be converted to mgdl and stored

Isn't that much easier ?

Maybe it's not always clear that a value is in mgdl, but I think that's a matter of adding comments

**Comment by opsb** [comment]
I wasn't aware that values were always kept in mgdl. 

If you add comments where would you add them? The bg values are used throughout the codebase, do you add a comment on each function/variable? If you add a new function do you remember to add the comment there as well? I'd argue that using comments to document this sort of information is more work and more error prone.

On the other hand using the type system will automate the documentation and enforcement of the values. It allows the compiler to guide the developer and rules out any bugs that might occur because the developer didn't see a comment or just plain forgot.

I'm new to Swift and coming from a static typing background in languages where this is fairly standard practice so perhaps it's just what I'm used to. I do feel that the compiler could offer useful assistance here though, particularly for newcomers to the codebase.

**Comment by JohanDegraeve** [comment]
Yes every variable every function and even every statement I try to document.
I should be able to read and understand the code without reading the code. To achieve this I very often writen down in comments why I do things and not only what. That's probably not feasibly but I try to reach it anyway.
I should be able to understand what a function does by clicking 
We're not at work here so we should have some more time to achieve this.

BGReading.calculatedValue clearly not commented. None of the core data class attributes is actually. I'll make time to do this.

As far as I know Swift is also static typing.

**Comment by opsb** [comment]
Ok I think there's a difference of philosophies here so I'll close this and try to stick with the style that you're going for.
