### ISSUE TITLE
Snoozing and Alert sounds

### ISSUE THREAD

**Issue by zshh** [JohanDegraeve/xdripswift#69]
Hi,

I know pressing "Snooze" in the app says it hasn't been completely implemented, but I thought I would list few things as wish list.

1. Be able to snooze from within app (preemptively). For example if I expect high values next 2 hours, it would be nice to be able to snooze them before they happen

2. List of currently enabled snooze(s) and ability to cancel/clear them

3. When you snooze high or low for lets say 1 hour, if value temporary fluctuates below the threshold and again goes high, snooze should still be active (that't not the case)
This is frequently seen with Libre if you lay on the arm etc
Example, 

BS is 10.5
High Alert kicks in
You snooze it for X minutes/hours
You happen to put pressure on Libre and value on next update could jump down to lets say 6.5
When pressure is released, value will jump again to 10.x which will sound the High Alert again (it should respect previous snoooze)

4. Snooze with condition. If value is high or low and you choose to snooze for certain time period, it would be nice to add condition to it with another value.

For example:
BS 10.5
High Alert kicks in
You choose to snooze for x hour
But you can also add condition that if its goes higher than 14 mmol, it should sound alert despite high alerts being snoozed.
(Same with low alerts)

5. Add more sounds for alerts

Let me know if this is already planned and this post is redundant or if you would like me to split it into several topics (didn't want to spam with multiple posts just yet :) )

@JohanDegraeve Many thanks for your work and effort!

**Comment by JohanDegraeve** [comment]
1. yes, will do it soon
2. yes, will do it soon
3. are you sure ? as far as I can read in the code there's no unsnooze. Note that if you close and relaunch the app, the snoozing is gone. It's not permenantly stored in the database
4. better to use very high or very low for this.
5. all i need is mp3's of maximum 30 seconds

No need to split, there's only 1 and 2 which belong together

**Comment by zshh** [comment]
Thank you Johan,

About (3), absolutely sure it re-triggers the audio alarm as soon as it hits above "high value" even tho you may have snoozed it for 1 hour 10-15 min before. App is always active for me, never close it unless it bugs out.

**Comment by bobhavlin** [comment]
Regarding Alerts, If I go into Settings->Alert Types and change Default to disabled, the alerts still pop up.  Particularly with the MissedReading alert.

**Comment by JohanDegraeve** [comment]
that should be only MissedReading Alert.
I'll create a seperate issue for that

**Comment by jarothmd** [comment]
Spike has many alarm sounds here: [https://github.com/SpikeApp/Spike/tree/master/src/assets/sounds](url) (Maybe some could be used in xDrip4iOS)

**Comment by JohanDegraeve** [comment]
presnooze and unsnooze implemented in e6a02921e287cd658a44a4c3751655b29fbbad22

**Comment by jarothmd** [comment]
The new sounds are great, wonderful. Thanx Johan.

Jamie Roth

On Aug 16, 2020, at 8:34 AM, Johan Degraeve <notifications@github.com<mailto:notifications@github.com>> wrote:

ATTENTION: This email originated from a sender outside of MCW. Use caution when clicking on links or opening attachments.
________________________________

Closed #69<https://urldefense.com/v3/__https://github.com/JohanDegraeve/xdripswift/issues/69__;!!H8mHWRdzp34!t3RMqfZyVglLw1VdqVG9QS2X6Dn_gto1lCeTAkLiPlFXyeNC5QSKVKcNXfIprw$>.
