### ISSUE TITLE
Previous readings after diconnected

### ISSUE THREAD

**Issue by sergiotome** [JohanDegraeve/xdripswift#71]
This request is when using a combination of Libre+Miaomiao, but can perfectly be applicable also to other devices....

When using xDrip+ in Android, after the app disconnects from miaomiao (i.e. phone is turned off, or connection is lost for any other reason), after reconnecting again, the app pulls data up to 8 hours back, which I'm assuming is the data available in Libre and that can be pulled from miaomiao. In this tool, when the app disconnects from miaomiao, and it reconnects again, only the last 4-5 readings are pulled, and everything else is lost. My request therefore is to pull as much as possible all missing data once reconnecting to the device, and send that data to nightscout like any other reading. Taking into account that with iOS 13 the app disconnects more often, would that be possible so that at least we minimize the amount of missing data after a disconnect?

**Comment by JohanDegraeve** [comment]
when disable oopweb the ios app also pulls 24 hours of data.
Not if oopweb is used.

How is it in xdrip+ ? does it pull all data if web oop is used ?

**Comment by sergiotome** [comment]
Yes, in Android it was pulling the last 8 hours of data (that is all information that the libre stores at a given point in time) even with OOP enabled. However, when I was using xDrip+ there was not a web OOP, but rather a separate app that you had to install in addition to xDrip. If that has changed in Android and they use webOOP now, I’m not sure if something may have changed with regards to how much data gets pulled wish I still had my old phone to test it!)

**Comment by JohanDegraeve** [comment]
see 2c05a0d614d4832b4050314695bbff1a3c6c9570

**Comment by sergiotome** [comment]
Can’t wait to test it. Thanks!!

**Comment by JohanDegraeve** [comment]
I have the impression that the values make a jump after collecting historic values. But I may be wrong, my sensors make lots of jumps

**Comment by sergiotome** [comment]
Yeah, I noticed something similar. Not perfect, but better than nothing...

![1A1EB54B-80AE-40D6-809C-3961E053FBA2](https://user-images.githubusercontent.com/16870246/73793754-4b7fd200-47a7-11ea-97db-adaa8bf7a40c.jpeg)
