### ISSUE TITLE
Implement Dexcom G6 8G 8H transmitter collection

### ISSUE THREAD

**Issue by bobhavlin** [JohanDegraeve/xdripswift#76]
Feature request.

Parallel to implementation of "Native Mode" in xDrip+:

https://github.com/NightscoutFoundation/xDrip/blob/master/app/src/main/java/com/eveningoutpost/dexdrip/G5Model/FirmwareCapability.java

https://github.com/NightscoutFoundation/xDrip/blob/master/app/src/main/java/com/eveningoutpost/dexdrip/Services/Ob1G5CollectionService.java

**Comment by trauts2** [comment]
Any plans for this in the near term?

**Comment by JohanDegraeve** [comment]
supported since 4.9.0
