### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by Pin77** [JohanDegraeve/xdripswift#78]
Hi Johan,

I am aware this are only cosmetics.. but is it possible for you to implement some kind of a dark mode?
Sometimes during the night i like to keep the phone on the charger and the app constantly open, so i can just take a peek on BG...
Thanks.

**Comment by JohanDegraeve** [comment]
did you think about getting an M5Stack ? xdrip connects with bluetooth to it (or Wifi if you think the project Martin Lukasek)

**Comment by Pin77** [comment]
I apologize for not being clear. I thought about app being literary black (dark mode). 
Pure cosmetics....

Cheers.

**Comment by JohanDegraeve** [comment]
I understood. Dark mode should probably not be difficult, It's just that I'm busy with some other stuff.

But I think M5Stack might be a good alternative. No need to keep your phone unlocked all the time.

**Comment by JohanDegraeve** [comment]
fix in f890014c9a00065d6cc102fafdb2533279a10957
