### ISSUE TITLE
Status Sensor vs Stop and Start

### ISSUE THREAD

**Issue by miki3421** [JohanDegraeve/xdripswift#79]
Hi @JohanDegraeve, in this version i'm struggling with the Button Stop/Start and Status. 
often i'm stopping the sensor instead of check the status. Can you move the stop button or just put a question (do you want stop the sensor? )
Thanks anyway for the amazing just that you've done. 

Michele

**Comment by JohanDegraeve** [comment]
Transmitter status moving to the second tab (where there's now the M5Stack and Watlaa), this should solve your issue.

**Comment by JohanDegraeve** [comment]
bluetooth redesign has made progress.
Transmitter status will be visible in seperate tab.
The "transmitter" button in the home screen will be renamed to "sensor".

I hope this will be released in a few weeks.
