### ISSUE TITLE
Sensor Start

### ISSUE THREAD

**Issue by bubbledevteam** [JohanDegraeve/xdripswift#8]
Hi，Johan

I paired Bubble with xdrip,but the sensor status is :not started ,and there is no way to start the sesnor in xdrip,in fact the sensor was started 3 days ago by Librelink App.

**Comment by JohanDegraeve** [comment]
I assume you tested this before by first using a MiaoMiao, start the sensor, then you switched to Bubble ?

There's two solutions : 

- In canDetectNewSensor, return false for Bubble : https://github.com/JohanDegraeve/xdripswift/blob/master/xdrip/Transmitter/CGMBluetoothTransmitter/Generic/CGMTransmitter.swift#L108
- in CGMBubbleTransmitter.swift, find a way to detect a new sensor then call cgmTransmitterDelegate?.newSensorDetected()

For Blucon this is done here https://github.com/JohanDegraeve/xdripswift/blob/master/xdrip/Transmitter/CGMBluetoothTransmitter/Libre/Blucon/CGMBluconTransmitter.swift#L357

MiaoMiao has a specific opcode for newSensor

**Comment by JohanDegraeve** [comment]
can you try the latest commit in master ?

**Comment by bubbledevteam** [comment]
fixed. 2nd solution worked.

thanks
