### ISSUE TITLE
Displays "-0" instead of "0" when there is no BG change (mg/dl)

### ISSUE THREAD

**Issue by paulplant** [JohanDegraeve/xdripswift#84]
A minus zero is often shown where the rounded BG delta is <1.

Not sure if this also affects mmol/l or just mg/dl

![image](https://user-images.githubusercontent.com/37302780/75147238-1eb34080-56fd-11ea-9ff2-ae48a13c5038.png)

Edit: Confirmed also in mmol/l:

![image](https://user-images.githubusercontent.com/37302780/75148393-ccbfea00-56ff-11ea-984d-9a0a716192cd.png)

Nightscout convention is to show zero changes as positive:

![image](https://user-images.githubusercontent.com/37302780/75148420-e7925e80-56ff-11ea-9142-affbdb1ba099.png)

**Comment by JohanDegraeve** [comment]
fix in 65a7eb0ca8b3b14dbfca7fb23bd6cab0bc77946c
