### ISSUE TITLE
Develop Branch is not working with Blucon. 

### ISSUE THREAD

**Issue by miki3421** [JohanDegraeve/xdripswift#88]
Hi, I tried the Develop Branch but is working. 
When I'm tring to add the Blucon device during the scan phase is crashing with the errore attached. 

<img width="1920" alt="Screenshot 2020-04-12 at 17 23 32" src="https://user-images.githubusercontent.com/42601846/79073118-04e9af00-7ce5-11ea-84e3-c9fcff058ef8.png">

**Comment by JohanDegraeve** [comment]
I've made a new commit, can you pull the development branch and try again ?

**Comment by miki3421** [comment]
Now is working, however if i'm pressing the button "start Sensor" I can't exit from the window. 
attached the screenshot 
![IMG_0097](https://user-images.githubusercontent.com/42601846/79076588-9b28cf80-7cfb-11ea-9732-facce4b069d4.PNG)

**Comment by miki3421** [comment]
even the high alert notification. 
![IMG_0098](https://user-images.githubusercontent.com/42601846/79076677-5c474980-7cfc-11ea-853e-d25e0aa96d2a.PNG)

**Comment by JohanDegraeve** [comment]
did you merge the branch tempFixPickerView ?
this should do it in a terminal session, in the root folder of your project :
git merge tempFixPickerView

**Comment by miki3421** [comment]
No sorry. I forked and I've done now. Next alert I can check. Meanwhile I can anticipate that even this BT stack sometime is crashing. Now I'm trying to keep the app as much as possibile in debug to track why. It's happening sometime when I'm in the garden. It's something related to the Wi-Fi connection. Do you have some suggestions? 
Thanks @JohanDegraeve for your amazing job.

**Comment by JohanDegraeve** [comment]
Is it crashing ? Or does it just lose and no re-establish the bluetooth connection ?
Blucon is known to be rather unstable.
But it can also happen with other devices like MiaoMiao.

iOS also has some unknown rules for apps running in the background. I experienced that the connection remains more stable if I don't use NightScout. So it's strange that you say related to the Wi-Fi connection.

Why do you think that ?

**Comment by miki3421** [comment]
It’s absolutely a crash I need to reopen the app.

I’ve tried without Mobile connection, just with Wi-Fi and is crashing
anyway. Totally without internet connection is not crashing at all.

Can be something related to write values in Nightscout.
I’m using it ..

With the last version I’m not able to recreate the crash.
Let see if now is stable.

**Comment by miki3421** [comment]
Alert are working fine now.

**Comment by JohanDegraeve** [comment]
Yes it looks like something related to NightScout

**Comment by miki3421** [comment]
I will try to catch the error. You can close this issue. Thank
