### ISSUE TITLE
Transmitter screen is not showing in Spanish 

### ISSUE THREAD

**Issue by paulplant** [JohanDegraeve/xdripswift#96]
Even though the iPhone language is set to Spanish and the rest of the app is displaying correctly in this locale, the transmitter screen still shows in English

![98343257_2563045237251876_6605300027801731072_n](https://user-images.githubusercontent.com/37302780/82315516-b0181300-99cb-11ea-9bad-bc7035c8a70f.jpg)

**Comment by paulplant** [comment]
Fixed in https://github.com/JohanDegraeve/xdripswift/pull/99

**Comment by JohanDegraeve** [comment]
I'll close it :)
